services:
  api:
    build: .
    image: barcode-generator-api:1.0.0
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - barcode_generator
    restart: unless-stopped
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - barcode_generator
    restart: always
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - barcode_generator
    restart: always

networks:
  barcode_generator:
    name: barcode_generator_network
    driver: bridge

volumes:
  postgres_data:
    name: barcode_generator_postgres_data
  redis_data:
    name: barcode_generator_redis_data
