-- ----------------------------
-- Records of categories
-- ----------------------------
INSERT INTO "public"."categories" ("code", "name") VALUES ('1011', 'MEN | BLAZER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1012', 'MEN | CARDIGAN');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1013', 'MEN | CLOTHING (mix)');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1014', 'MEN | COAT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1015', 'MEN | BOARD SHORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1016', 'MEN | JACKET');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1017', 'MEN | JAS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1018', 'MEN | JUMPSUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1019', 'MEN | LONG PANTS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1020', 'MEN | MOESLEM');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1021', 'MEN | PIJAMAS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1022', 'MEN | POLO SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1023', 'MEN | SAFARI');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1024', 'MEN | SARUNG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1025', 'MEN | SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1026', 'MEN | SHORT PANTS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1027', 'MEN | SUIT SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1028', 'MEN | SWEAT SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1029', 'MEN | SWEATER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1030', 'MEN | SWIMSUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1031', 'MEN | T SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1032', 'MEN | TRAVEL BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1033', 'MEN | UNDERWEAR');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1034', 'MEN | VEST');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1035', 'MEN | WAIST BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1036', 'MEN | SPORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1037', 'MEN | CLOTHES SUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1038', 'MEN | CLOTHING SPORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1101', 'LADIES | AEROBIC SUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1102', 'LADIES | BLAZER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1103', 'LADIES | BLOUSE');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1104', 'LADIES | BRA');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1105', 'LADIES | CARDIGAN');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1106', 'LADIES | CLOTHES SPORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1107', 'LADIES | CLOTHES SUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1108', 'LADIES | CLOTHING (mix)');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1109', 'LADIES | CLOTHING SPORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1110', 'LADIES | COAT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1111', 'LADIES | CROP TOP');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1112', 'LADIES | DRESS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1113', 'LADIES | GAMIS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1114', 'LADIES | HOODIES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1115', 'LADIES | HOT PANTS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1116', 'LADIES | JACKET');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1117', 'LADIES | JUMPSUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1118', 'LADIES | KIMONO');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1119', 'LADIES | LEGGING');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1120', 'LADIES | LONG DRESS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1121', 'LADIES | LONG PANTS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1122', 'LADIES | MOESLEM');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1123', 'LADIES | PIJAMAS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1124', 'LADIES | POLO SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1125', 'LADIES | SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1126', 'LADIES | SHORT PANTS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1127', 'LADIES | SKIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1128', 'LADIES | SKORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1129', 'LADIES | SUIT SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1130', 'LADIES | SWEAT SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1131', 'LADIES | SWEATER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1132', 'LADIES | SWIMSUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1133', 'LADIES | T SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1134', 'LADIES | TANK TOP');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1135', 'LADIES | UNDERWEAR');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1136', 'LADIES | VEST');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1137', 'LADIES | WAIST BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1138', 'LADIES | KAIN BATIK');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1139', 'LADIES | PONCHO');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1201', 'KIDS | AEROBIC SUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1202', 'KIDS | BLOUSE');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1203', 'KIDS | BRA');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1204', 'KIDS | CARDIGAN');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1205', 'KIDS | CLOTHES SPORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1206', 'KIDS | CLOTHES SUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1207', 'KIDS | CLOTHING (mix)');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1208', 'KIDS | CLOTHING SPORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1209', 'KIDS | COAT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1210', 'KIDS | CROP TOP');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1211', 'KIDS | DRESS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1212', 'KIDS | HOODIES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1213', 'KIDS | HOT PANTS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1214', 'KIDS | JACKET');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1215', 'KIDS | JUMPSUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1216', 'KIDS | KIMONO');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1217', 'KIDS | LEGGING');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1218', 'KIDS | LONG PANTS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1219', 'KIDS | MOESLEM');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1220', 'KIDS | PIJAMAS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1221', 'KIDS | POLO SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1222', 'KIDS | SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1223', 'KIDS | SHORT PANT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1224', 'KIDS | SHORT PANTS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1225', 'KIDS | SKIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1226', 'KIDS | SKORT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1227', 'KIDS | SLING BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1228', 'KIDS | SUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1229', 'KIDS | SUIT SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1230', 'KIDS | SWEAT SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1231', 'KIDS | SWEATER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1232', 'KIDS | SWIMSUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1233', 'KIDS | T SHIRT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1234', 'KIDS | TANK TOP');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1235', 'KIDS | UNDERWEAR');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1236', 'KIDS | VEST');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1237', 'KIDS | WAIST BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1238', 'KIDS | JAS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1239', 'KIDS | LONG JOHN');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1240', 'KIDS | PONCHO');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1241', 'KIDS | JUMPER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1301', 'BAG n SHOES | BACK PACK');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1302', 'BAG n SHOES | HAND BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1303', 'BAG n SHOES | SHOES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1304', 'BAG n SHOES | SLING BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1305', 'BAG n SHOES | SLIPPER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1306', 'BAG n SHOES | TRAVEL BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1307', 'BAG n SHOES | WAIST BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1308', 'BAG n SHOES | BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1309', 'BAG n SHOES | CHEST BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1310', 'BAG n SHOES | BUM BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1311', 'BAG n SHOES | BEAUTY CASE BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1401', 'ACCESSORIES | BANDO');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1402', 'ACCESSORIES | BELT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1403', 'ACCESSORIES | BROS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1404', 'ACCESSORIES | EAR CAP');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1405', 'ACCESSORIES | GLOVES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1406', 'ACCESSORIES | HAIRBANDS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1407', 'ACCESSORIES | HAND GLOVES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1408', 'ACCESSORIES | HAT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1409', 'ACCESSORIES | SCARFT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1410', 'ACCESSORIES | SKULLCAPS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1411', 'ACCESSORIES | SOCKS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1412', 'ACCESSORIES | SWIMSUIT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1413', 'ACCESSORIES | SYAL');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1414', 'ACCESSORIES | TIE');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1415', 'ACCESSORIES | TOWEL');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1416', 'ACCESSORIES | WALLET');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1417', 'ACCESSORIES | SUN GLASSES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1418', 'ACCESSORIES | FASHION WINGS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1419', 'ACCESSORIES | PIN');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1420', 'ACCESSORIES | BUFF');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1421', 'ACCESSORIES | test data');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1422', 'ACCESSORIES | TALI HP');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1423', 'ACCESSORIES | BAG CHARM');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1501', 'TOYS n VIDEO GAME | DOLLS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1601', 'BATH | BLANKET');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1602', 'BATH | MAT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1603', 'BATH | TOWEL');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1604', 'BATH | UMBRELLA');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1605', 'BATH | BATH ACCESORIES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1606', 'BATH | HANDKERCHIEF');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1701', 'MOESLEM | VEIL');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1702', 'MOESLEM | PRAYER RUGS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1801', 'FITNESS AND OUTDOOR');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1901', 'OUTERWEAR | COAT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('1902', 'OUTERWEAR | RAIN COAT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2001', 'SUPPLY | PLASTIC BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2002', 'SUPPLY | PROMOTION GOODS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2003', 'SUPPLY | WRAPING PAPER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2004', 'SUPPLY | PAPER BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2005', 'SUPPLY | SHOPPING BAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2101', 'NON TRADE | COMPUTER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2102', 'NON TRADE | LABEL n TAG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2103', 'NON TRADE | PRINTER BARCODE');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2201', 'OPEN CODE | OPEN CODE');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2202', 'OPEN CODE | SERVICES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2301', 'HAIR ACCESSORY | BANDANA');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2302', 'HAIR ACCESSORY | BANDO');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2303', 'HAIR ACCESSORY | BROS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2304', 'HAIR ACCESSORY | COMB');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2305', 'HAIR ACCESSORY | HAIRBANDS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2306', 'HAIR ACCESSORY | TIE THE VEIL');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2307', 'HAIR ACCESSORY | TOOLS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2308', 'HAIR ACCESSORY | WALLET');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2401', 'JEWELRY | BRACELET');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2402', 'JEWELRY | NECKLACE');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2403', 'JEWELRY | RING');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2501', 'PERSONAL ACCESSORY | KEY CHAIN');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2601', 'JEWELRY | EARRINGS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2701', 'BEAUTY TOOLS n ACCESSORIES | TOOLS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2702', 'BEAUTY TOOLS n ACCESSORIES | SPONGE');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2703', 'BEAUTY TOOLS n ACCESSORIES | HAIR ACCESORIES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2704', 'BEAUTY TOOLS n ACCESSORIES | NAIL ACCESSORIES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2801', 'NON FASHION | MINERAL WATER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2802', 'NON FASHION | PLASTIC EQUIPMENT');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2803', 'NON FASHION | HANDPHONE ACCESSORIES');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2804', 'NON FASHION | STATIONERY');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2805', 'NON FASHION | LUNCH BOX');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2806', 'NON FASHION | TISSUE BOX');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2807', 'NON FASHION | PHOTO ALMBUM');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2808', 'NON FASHION | BOOKS');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2809', 'NON FASHION | MEDICAL PLASTER');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2810', 'NON FASHION | PIN');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2811', 'NON FASHION | FOOD');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2812', 'NON FASHION | CARD BOX');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2813', 'NON FASHION | HOUSEHOLD');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2814', 'NON FASHION | GLASSES CASE');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2815', 'NON FASHION | PELAMPUNG');
INSERT INTO "public"."categories" ("code", "name") VALUES ('2901', 'CLOTHING MIX | CLOTHING MIX');
