-- ----------------------------
-- Records of suppliers
-- ----------------------------
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0000', 'Supplier Umum');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0001', 'PT. Blesindo Mega Anugerah');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0002', 'APANG/PT. SEJAHTERA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0003', 'DELAMI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0004', 'MIMING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0005', 'PT MULYA LESTARI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0006', 'LINK STOCK-EDDY HANGER');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0007', 'ISHAK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0008', 'TATANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0009', 'LELLY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0010', 'PT DAEHAN GLOBAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0011', 'NOVA COLL/SUWARDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0012', 'CHRISTIANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0013', 'METRO EXIM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0014', 'TRI PRIMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0015', 'SHERLY/YENI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0016', 'MAHKOTA KENCANA/LINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0017', 'LITA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0018', 'FERRY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0019', 'MISS PARK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0020', 'IRENE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0021', 'AGUS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0022', 'HANY/DADY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0023', 'AKIUN (WISH COLLECTION)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0024', 'SUZANNA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0025', 'CECILIA SARJONO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0026', 'PETRUS/PUSAT EXPORT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0027', 'SANDY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0028', 'YULIUS/CAROLINE II');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0029', 'LENNY SUTANDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0030', 'YOSSY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0031', 'IKUANG/ITINK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0032', 'TANTI(636)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0033', 'DANI/M RAMDHAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0034', 'BERNADETTE NATALIA/PT SINAR MATAHARI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0035', 'PT DINEXINDO/ADI KARYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0036', 'KWIENG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0037', 'PT INKORDAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0038', 'NANA CLT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0039', 'LIVIA WINARDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0040', 'BERNARD');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0041', 'LENI SUGIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0042', 'BUDIYANTO MULYANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0043', 'HENRY/RUDY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0044', 'NANA COLECTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0045', 'AK GARMENT /ASHOK K. H');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0046', 'ANSYE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0047', 'VIVALDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0048', 'YANDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0049', 'DARUSMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0050', 'SANNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0051', 'CV PERSADA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0052', 'IIS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0053', 'SATRINDO GARMENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0054', 'POPO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0055', 'PT COCA COLA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0056', 'USIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0057', 'CARSONO CIBUBUR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0058', 'HARTONO LILY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0059', 'LOREN FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0060', 'CYBY CITRA BUSANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0061', 'MR KIM SENTUL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0062', 'ADE FEZA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0063', 'BAHARI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0064', 'SINGAPORE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0065', 'ELISABET/BUYUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0066', 'NENI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0067', 'PT JABA GARMINDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0068', 'KOKEM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0069', 'H KUSNADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0070', 'NINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0071', 'INDRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0072', 'BUSANA IDOLA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0073', 'DENNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0074', 'YONA/VISANZA/TJONG SING SIANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0075', 'PT SAMANTRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0076', 'BIRGITA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0077', 'HELVI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0078', 'ICAY/ANDY/IHING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0079', 'BUDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0080', 'MUHAMAD AHMAD 082');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0081', 'MIMI/INDOCITRA BUSANA /CANCAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0082', 'MIKE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0083', 'BENNY PRECCY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0084', 'PT LESTARI SANTIKA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0085', 'FENTY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0086', 'PT INDUSTRI INDAH JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0087', 'DONI MAGA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0088', 'DANIEL TJANDRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0089', 'LING-LING 11');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0090', 'SALUM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0091', 'HERMAWAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0092', 'HILTON');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0093', 'BUSUR MAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0094', 'ERNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0095', 'ROMMY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0096', 'FIT-U');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0097', 'SINTA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0098', 'ADRIANUS (AA)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0099', 'PT BPG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0100', 'HARRY GUNAWAM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0101', 'YANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0102', 'WILLFRED');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0103', 'IVAN/ENNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0104', 'IYAN HARDIANSYAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0105', 'GITA W');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0106', 'INDAH JAYA DOMPET(HEINCE)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0107', 'M JOHAN(201');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0108', 'FREDDY TURANGAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0109', 'LAURENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0110', 'AKIONG/HOWTEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0111', 'PAULUS CANDRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0112', 'RAJA KAOS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0113', 'SUSI CARLA/FAJAR TERANG ABADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0114', 'TRIMANDIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0115', 'LENNY PANDU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0116', 'PT. PRIMA PERAHU AGUNG/CLN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0117', 'SENDJAJA GUNAWAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0118', 'SUWARNO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0119', 'ANDRI K');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0120', 'SURESH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0121', 'JUL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0122', 'ACIEN/HERRIS TRADING (AT)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0123', 'IING BPR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0124', 'DEVA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0125', 'ANDY RAUM/VERONICA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0126', 'LARISH F');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0127', 'ABDILLAH/FADILLAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0128', 'AXEL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0129', 'BOLA MAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0130', 'ADIS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0131', 'RENA/ARGA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0132', 'MITRA COLLECTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0133', 'MAKRO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0134', 'MODIFIKASI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0135', 'UCENG/RINA LATIFAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0136', 'LITTLE INK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0137', 'BAYU (BY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0138', 'HENNY LIMANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0139', 'TEGUH/SINAR SELATAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0140', 'LISNA/HERMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0141', 'MINDA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0142', 'LIA TAMAN MUTIARA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0143', 'GRANDE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0144', 'LUMBUNG PADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0145', 'KARAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0146', 'DEVA I PUTRA / SEMANGAT ERA MANDIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0147', 'MEGAWATI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0148', 'ENDI (EI)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0149', 'YOGO BEKASI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0150', 'IPE PURWANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0151', 'ROY (KALENDER)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0152', 'ASEP BERLIAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0153', 'MULTI BROTHER');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0154', 'GUNAWAN T');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0155', 'UNIQUE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0156', 'ERWI LEGOK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0157', 'ADE FH/FA-FA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0158', 'PT GMT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0159', 'H MADI 730');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0160', '"ANDY LUKMAN 700');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0161', 'BUDI WILKY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0162', 'AMIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0163', 'WIYANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0164', 'MARK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0165', 'EDWAN SHARON');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0166', 'PT SOCKA FARGE INDONESIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0167', 'AAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0168', 'SUPLIER MIX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0169', 'JENNY SEMARANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0170', 'TEJA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0171', 'PAULINE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0172', 'MUMPHIS(MM)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0173', 'SUHAIMI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0174', 'ANO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0175', 'FAHMI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0176', 'SUWOTO/ATIYAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0177', 'INNA APPAREL/CHRISTIANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0178', 'DARMA MERUA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0179', 'ENGKOS (ES)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0180', 'KAMPUNG DAUN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0181', 'KOMALA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0182', 'STEVE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0183', 'EXPORT STATION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0184', 'PT WISKA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0185', 'BENNI SUHERLAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0186', 'ICAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0187', 'MEGAWATI W/ACCHEDYA COLLECTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0188', 'MANOJ D MUN WANI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0189', 'NAEEM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0190', 'KAMAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0191', 'MARINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0192', 'ANDI KIM (AK)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0193', 'TOTO SUTANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0194', 'AAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0195', 'H. MAS UD (234/203)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0196', 'AKUY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0197', 'ANDREW');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0198', 'ANDRI LAPUMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0199', 'PT KAPASINDO PRIMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0200', 'LILY BHC/LILY DEVIANI HIDAYAT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0201', 'WIMA BUSANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0202', 'SIAW HUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0203', 'ADENG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0204', 'PAKAR SEMBILAN/IRFAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0205', 'ROSINI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0206', 'LISKE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0207', 'HANDOYO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0208', 'MAIDASRIL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0209', 'IMEL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0210', 'DILLA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0211', 'PT DAESE GARMENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0212', 'JORDAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0213', 'ROBERT RAFFAEL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0214', 'HORNEST');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0215', 'SANTOSA JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0216', 'PT SINARRIMPEx');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0217', 'BENNY ANDERSON');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0218', 'PT. GISTEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0219', 'UNGARAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0220', 'SHERLY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0221', 'TOKO M2');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0222', 'IING/SUSAN BLOOMING (547)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0223', 'PT YOSAFAT ADIDAYA/LUCAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0224', 'S. SIMAMORA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0225', 'H MAS UD (234/203)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0226', 'PT MASCOTINDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0227', 'JESSICA/SELVIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0228', 'PT MGP ( MITRA GARINDO PERKASA )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0229', '"BENNY T 239');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0230', 'H AWING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0231', 'GCR/GRACE BR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0232', 'LUCAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0233', 'ANTON L.BCA ( 745/237/243/172)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0234', 'EDI PURNAMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0235', 'KAROLINA/CAMAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0236', 'UNGARAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0237', 'IBU I YEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0238', 'SUHANDI/BANDUNG STOCK LOT CENTRE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0239', 'YUSUF 475');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0240', 'LILY UTARIA/JKT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0241', 'RIENA SUSANTI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0242', 'IING BARU/CAKRAWALA 647');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0243', 'PT CAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0244', 'ANITA FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0245', 'ERLIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0246', 'BINA CITRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0247', 'ROMLI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0248', 'PT INDUSTRI INDAH JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0249', 'LILI/TAN MEI LIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0250', 'YULIAWATI CHRISTIAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0251', 'MAYOR JUN (261/338)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0252', 'YANTI/VALERIE COLL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0253', 'EKA/BENYAMIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0254', 'PT PICAERINDO ABADI JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0255', 'HENDRI/VINCE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0256', 'JAYA MULYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0257', 'TWIG HOUSE/KIOK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0258', 'EUGENIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0259', 'PT PONI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0260', 'IWAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0261', 'KAYDEE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0262', 'GAUDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0263', 'SUN TJIANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0264', 'ACIM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0265', 'PT CAS (253/418/503/638/275)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0266', 'LISA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0267', 'GENTA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0268', 'MR GOFU (713/622/278)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0269', 'AMIRA (AM)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0270', 'NELLY NURDIANI/WINS FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0271', 'CAROLINE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0272', 'UCHIE/SISKA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0273', 'ROBIN II');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0274', 'SANDRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0275', 'REI SUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0276', 'WANDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0277', 'ANNA DESIGN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0278', 'QUICK (Q)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0279', 'NOVA FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0280', 'PT DUTA MANDIRI PERKAS (DMP)/HERMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0281', 'T.PENGKOLAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0282', 'ELIA/BIG FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0283', 'BUDI/ALEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0284', 'INDRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0285', 'PT JAVA INDO PRINT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0286', 'BARNUS/VILLICIANUS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0287', 'PIPIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0288', 'PT PESONA GARMENT/DANNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0289', 'AAS UNGARAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0290', 'DALANTA BUKIT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0291', 'ANDI LUKMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0292', 'CANIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0293', 'THAI THAI SHOP');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0294', 'BIG PULL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0295', 'HARISH KUMAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0296', 'PD FAJAR PRIMA /BUDI BENNY (FP)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0297', 'CV BINTANG ARGO/AGUS SISWANDY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0298', 'NOVI/BEAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0299', 'PT MEGA/PRAKASH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0300', 'TOKO 32 ANDIR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0301', 'SHERLY INDRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0302', 'TEGUH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0303', 'JAYA LESTARI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0304', 'YAN SETIO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0305', 'STEPHANUS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0306', 'BUMIWANA USAHA JAYA ( BUJ )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0307', 'SURONO (SO)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0308', 'JOHAN SUSANTO/INTITEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0309', 'PT ISANTI JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0310', 'ICT/ENGGARYANI IRAWAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0311', 'NATATEX/KURNIADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0312', 'MING YEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0313', 'BUSANA INDAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0314', 'PT BPG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0315', 'BERKAT JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0316', 'METRO GARMENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0317', 'MULIA JAYA/EKRILO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0318', 'LUCA BOSSI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0319', 'ROSITA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0320', 'PT.AMEYA LIVINGSTYLE (AL)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0321', 'ULUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0322', 'AGNES');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0323', 'BENNY KBJ');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0324', 'MAYOR JUN 261');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0325', 'WILLIAM INE (WI)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0326', 'CARGO FACTORY OUTLET');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0327', 'BLOSSOM FO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0328', 'WINDRA DENIM (WD)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0329', 'BLACK MARKET');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0330', 'UJANG SULAEMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0331', 'PT GIVEMAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0332', 'YUSITO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0333', 'SUTRISNO/SINSIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0334', 'MOI FO JKT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0335', 'KIM IN SOO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0336', 'MEGA/ JASEON');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0337', 'ANUGERAH PRATMA BUSANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0338', 'TERMINAL MODE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0339', 'PT.TYFOUNTEX INDONESIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0340', 'AGUS / HERI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0341', 'HERMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0342', 'STYLE/NICE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0343', 'BUAH BATU STOCK LN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0344', 'LEONARDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0345', 'PT SINAR APPAREL INDONESIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0346', 'BEST CHOICE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0347', 'ANDRI SOKA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0348', 'VICKY TOYS/DAVID');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0349', 'PT BHARAT TRADING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0350', 'JANTY (JY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0351', 'EMMY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0352', 'EL-HA FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0353', 'ALBERT TJAHYADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0354', 'FARID');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0355', 'CHRISTINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0356', 'HANNY G');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0357', 'HANNIE DESIGN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0358', 'PT STARINDO JAYA UTAMA/ IBU II');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0359', 'SM GARMENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0360', 'RAJU/DAVE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0361', 'I KHWANUDIN /UD SEDERHANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0362', 'PT ARTA RAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0363', 'LOTUS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0364', 'SIPAHUTAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0365', 'LILIYANTI ONGGOWASITO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0366', 'SINAR MAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0367', 'GRAHA BUSANA LESTARI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0368', 'YITNO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0369', 'SHELLY MALIKI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0370', 'TUWUH PRATIWI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0371', 'DARMADJI/UD SEDERHANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0372', 'WIJAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0373', 'LIA/LICOS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0374', 'B BOS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0375', 'AAN UNGARAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0376', 'DJAP/ANTONI (DA)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0377', 'AKIET');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0378', 'DAVE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0379', 'HERU/RYAN COLLECTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0380', 'YANCE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0381', 'CAREFOURE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0382', 'MARIA (MA)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0383', 'ERNI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0384', 'FREDDY TANU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0385', 'RAMA TUNGGAL/RAMADHAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0386', 'CV TIRTA KENCANA  MANDIRI/DADANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0387', 'PT UNGARAN SARI(246');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0388', 'HANSON INDUSTRI UTAMA TBK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0389', 'WINS FASHION/NELLY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0390', 'YOGYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0391', 'WORLD SHOP 9999');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0392', 'PT ESWON  MAS SENTOSA/MR HONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0393', 'BRASCO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0394', 'UD RIZKY SUKSES MANDIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0395', 'MR KEVIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0396', 'TUNG MEI /MDC');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0397', 'CARVIENO /CV JKL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0398', 'MAJESTY COLL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0399', '"M&M DAGO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0400', 'LIDIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0401', 'DIAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0402', 'MR LEE  WAN YOUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0403', 'PT CAS 253');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0404', 'PT SANGWOO /MR OH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0405', 'LIONG SUSAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0406', 'KING COLLECTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0407', 'EMY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0408', 'DOENG (DG)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0409', 'AAM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0410', 'THE BEAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0411', 'DJAYA FASHION/EKA DJAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0412', 'AYUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0413', 'RUDI CEMPAKA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0414', 'DINDRO SUSANTO (DS)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0415', 'ERI SALATIGA ( ES )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0416', 'ROHMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0417', 'SUBHI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0418', 'CITRA BUSANA INDONESIA/MITRA SUKSES');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0419', 'MARTIN B');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0420', 'STEVEN/RINI (MAJU INDAH GARMENDO)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0421', 'MEKAR JAYA MANDIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0422', 'BUDI ALDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0423', 'INDO GROSIR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0424', 'HERWAN/TOTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0425', 'BUCHARI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0426', 'YOCOCO BUSANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0427', 'PRIMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0428', 'THE BEAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0429', 'CIBADAK/PD TERUS MAKMUR/T.HEGAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0430', 'AMELIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0431', 'YUKI/ROSDIANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0432', 'METI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0433', 'TDM/FIVI (SANGKIONG)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0434', 'PT BPG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0435', 'IBU SETIAWAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0436', 'KETUT KRISBIANTORO (KK)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0437', 'SUMMIT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0438', 'MARCHE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0439', 'CORAL FO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0440', 'PT JAYA CAHYA AGUNG/VICTORIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0441', 'ATIYAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0442', 'ANES');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0443', 'SUSIE/SISILIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0444', 'HERITAGE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0445', 'VERONICA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0446', 'SASHA & POPY COLL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0447', 'TRI TUNGGAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0448', 'PARKIR FO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0449', 'TIMUR JAYA ABADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0450', 'INDO ANIL MANDIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0451', 'YACOCO BUSANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0452', 'TOKO HEGAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0453', 'TEDY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0454', 'KIKI SUSILO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0455', 'CIPTADI PRIMA MANDIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0456', 'KURNIA SENJAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0457', 'SINURAT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0458', 'HANAFI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0459', 'YUSUF 249');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0460', 'FERANCHICE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0461', 'PT VISTA MEGAH LESTARI (602)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0462', 'TWIG HOUSE/KIOK (TH)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0463', 'MELIA (616/722)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0464', 'JUMINI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0465', 'TRI JAYA/SYLVIA SUMARTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0466', 'YOHAN ONGGARA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0467', 'CYNTIA DEVY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0468', 'KING FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0469', 'KHATAM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0470', 'BERLINA (BA)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0471', 'VALENTIA/DIVA FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0472', 'PT ADETEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0473', 'KO KIKI ( KI )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0474', 'ZULKIFLI/MR HONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0475', 'NANA COLL/BENTLEY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0476', 'TERA LOVIANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0477', 'UNGARAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0478', 'BLESINDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0479', 'UK MANDIRI/BUDIONO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0480', 'MSK/MASUKAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0481', 'FEMALE FASHION/HANNY DESIGN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0482', 'GOLDEN FLOWER');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0483', 'BUSANA EXPORT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0484', 'HDR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0485', 'ANTON SASMITA/LONG INDUSTRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0486', 'PT BMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0487', 'PT CAS (253/418/503/638/275)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0488', 'HAIKAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0489', 'INDRAWATI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0490', 'TOHA (TA)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0491', 'FENTY/YOLA (288)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0492', 'JASON INTI GARMENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0493', 'JE T AIME/LINNA EFFERIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0494', 'CANIA URESI/SELVI(303)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0495', 'K.E.T');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0496', 'KOTA BUNGA/THOMAS SIHOMBING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0497', 'RICKO RIDWAN ( RR )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0498', 'ELEN/MADELAINE (EM)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0499', 'IRA S');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0500', 'ALNA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0501', 'MEGA IMPEXINDO/PRAKASH N M');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0502', 'MILLENIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0503', 'WALUYO/PSR CIPANAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0504', 'WINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0505', 'KINGS/PA ALVIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0506', 'FREUNDIN COLL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0507', 'ETHNIC INDONESIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0508', 'FENTIE JUVE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0509', 'RIZAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0510', 'TK ARDILLA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0511', 'ACING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0512', 'YANTO/BECXXA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0513', 'TK CIPANAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0514', 'PANCA TUNGGAL (PT)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0515', 'WAJEDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0516', 'INSPORT/BONAR ( IB )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0517', 'MR SIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0518', 'SPLISH SPLASH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0519', 'ABDILAH (FADILA/437/535)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0520', 'PT CIPTA BUSANA JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0521', 'NASRUL ( NS )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0522', 'PT KANCHAN JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0523', 'KAFIAT PRIMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0524', 'PT LEVIS STRAUSS INDONESIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0525', 'SB KIM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0526', 'BATAMTEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0527', 'KINS SWALAYAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0528', 'PERDANA GARMENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0529', 'GAUD');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0530', 'BLOOMING/IING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0531', 'FAISAL (651)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0532', 'LUMINA GARMENT/BUDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0533', 'ANITA S/TEA (594)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0534', 'PT RAJA BUSANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0535', 'YUSACK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0536', 'ARTA GLORI BUNGA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0537', 'NOVY/OKY SUGIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0538', 'LELLY (009)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0539', 'NOUVELLE/BPK DIDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0540', 'ACONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0541', 'ERATEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0542', 'JAYA ABADI/FIRMAN F H');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0543', 'NITA ANGGRAENI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0544', 'LITTLE INK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0545', 'LEMBANG INDAH GARMENT/VICTOR HERLIM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0546', 'ICE JEANS/JIMMY BUSANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0547', 'RISKA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0548', 'LILY YU/INDO PRIMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0549', 'WINS FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0550', 'BENNY (INDIA)/PT SURYA KENCANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0551', 'YANSEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0552', 'DIANA/MAKMUR SENTOSA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0553', 'UUNG SUJATNIKA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0554', 'HARRY/CANIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0555', 'IMELDA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0556', 'IDRUS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0557', 'HADI LIEM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0558', 'ANGGI ( AG )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0559', 'SRITEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0560', 'CABAZON');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0561', 'AYEP ( AP )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0562', 'PT SALLY/TOTONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0563', 'KERIS GALERIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0564', 'KHARISMA JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0565', 'AGUSTIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0566', 'NATA/GRITANIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0567', 'MIKE S HOUSE/CATTY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0568', 'PT.CHUNG SHUN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0569', 'SCOLL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0570', 'GUY GARMENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0571', 'ONEAL/MUHAMMAD HAFIDZ');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0572', 'TUNAS DARMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0573', 'IRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0574', 'XANADU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0575', 'XANDA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0576', 'CALISTA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0577', 'ANITA S/ TEA (550)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0578', 'M JOHAN ( 109/201/304/664)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0579', 'MINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0580', 'DIAMOND/KURNIAWAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0581', 'MEI-MEI/MARTIN (645)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0582', 'FO MIX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0583', 'RIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0584', 'SUHANDI (248)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0585', 'PT VISTA MEGAH LESTARI (477)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0586', 'AMOUR/DIDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0587', 'BAMBANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0588', 'LANI SETIADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0589', 'HANNIE / MY JOY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0590', 'IVAN JOESTAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0591', 'NENEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0592', 'RIDWAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0593', 'ELIZABETH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0594', 'BETTY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0595', 'KATHERINE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0596', 'AMOEBA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0597', 'V SUGIHARTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0598', 'FOREVER SALE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0599', 'MELIA (479/722)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0600', 'INKO BINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0601', 'DEDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0602', 'BERNARD WILLY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0603', 'KRISTAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0604', 'RENA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0605', 'ALEX JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0606', 'CORIE MANDIRI GARMINDO/CHYNTYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0607', 'FANNEKE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0608', 'ERIX KRISTIANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0609', 'NOVI/BOLA RATU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0610', 'SETIA AGUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0611', 'DADANG RUSLAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0612', 'YANTI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0613', 'ULE COLLECTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0614', 'IRNA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0615', 'PT PRIMA MANDIR INTISENTOSA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0616', 'SUSIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0617', 'TANTI (032)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0618', 'BABY TEAM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0619', 'PT CAS (253/418/503/638/275)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0620', 'VINS PRODUCTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0621', 'ANTONI (ANTON PADANG)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0622', 'MEDIATECH/FELIX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0623', 'PETER');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0624', 'HERMAWAN LEMBANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0625', 'MEI MEI (598)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0626', 'SUSI LESMANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0627', 'SHERLY/CAKRAWALA MULTI BUSANA (252)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0628', 'AGNES TAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0629', 'AAT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0630', 'DIANA CHRISTIEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0631', 'FAIZAL (548)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0632', 'KUMALA JKT/SHAYLA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0633', 'WITA/KARTINI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0634', 'TINA/FOUR STARS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0635', 'SINAR ANUGERAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0636', 'HANNY ATMAJA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0637', 'DARMADJI (386)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0638', 'HERMAN/MEGA CIPTA GARMINDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0639', 'PHILLIPS-VAN HEUSEN/SHELLY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0640', 'PT BPG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0641', 'JIMMY/CUN KING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0642', 'NAILA NOVARANTI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0643', 'PT. DEWHIRST');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0644', 'TEGUH/YOSSANO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0645', 'ENJANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0646', 'EDI HARMONI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0647', 'CHA-CHA/MELISA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0648', 'LUSY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0649', 'ARIFIN FLORENZA TEXTILE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0650', 'JCA SIANG- SIANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0651', 'PT SRI REJEKI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0652', 'VIVI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0653', 'SONU BHOJWANI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0654', 'KUSWANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0655', 'YANG-YANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0656', 'SHIRLY L/LILY FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0657', 'ROBERT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0658', 'TAJUR (BOGOR)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0659', 'KOTA BUNGA/BP SURYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0660', 'JEANI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0661', 'SHELLY/PVH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0662', 'IWAN/LALA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0663', 'YOPIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0664', 'BUANA SPORT/INDRA (718/728)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0665', 'IWAN/ANDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0666', 'ACHEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0667', 'RICKY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0668', 'MELIA479/616');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0669', 'YANTO WINATA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0670', 'BDM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0671', 'ASEP P');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0672', 'PETER BARU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0673', 'ANEKA JAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0674', '"BUANA SPORT/INDRA 718');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0675', 'PT.DANLIRIS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0676', 'H. MADI 164');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0677', 'AHMAD HOLOLI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0678', 'RUDI KOSWARA/PT GEMPITA MITRAKARYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0679', 'SARINA CHANDRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0680', 'ANDREY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0681', 'ALEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0682', 'YONAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0683', 'SEIZA/SIENDY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0684', 'TIONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0685', 'CAKRAWALA MULTI BUSANA/YENNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0686', 'RUMAH GAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0687', 'DINDRO SUSANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0688', 'VICTORIA MITRA LESTARI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0689', 'ANTON L BCA 745');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0690', 'HERMAN/TAMAN HOLIS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0691', 'PABRIK BADJOE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0692', 'DUNIA JAYA-PTB ANGKE KAV10-11');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0693', 'HEAVE CLOTHING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0694', 'MITRA SUKSES BERSAMA/CBI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0695', 'DENI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0696', 'ARJAN/HARNES');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0697', 'VANESSA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0698', 'HAMDANI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0699', 'SUP EX JATI ENGGAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0700', 'TITO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0701', 'FIE-FIE/SUN-SUN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0702', 'NOVI/RIDWAN (NICE)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0703', 'AWEN/KOTA KATUN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0704', 'BUDI CIBUBUR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0705', 'SHIEN-SHIEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0706', 'ARI JHONATAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0707', 'FARHAN UCOK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0708', 'HASIL BORDIR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0709', 'JOHANNA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0710', 'SYAHRUL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0711', 'MEDWEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0712', 'ANDRIAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0713', 'ESTI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0714', 'HALIM RAJA FO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0715', 'DAVID ANGGADA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0716', 'YEYIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0717', 'MAISIR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0718', 'JASWADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0719', 'STAR INDONESIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0720', 'ERIC');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0721', 'BAGOL SETIAWATI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0722', 'SUP MIX BRG OB');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0723', 'JOSSANO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0724', 'DAMAI TEXTILE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0725', 'ELAINE (ELLEN)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0726', 'TRI MANDIRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0727', 'PT.Aneka Label Indah');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0728', 'MASTER PRINT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0729', 'PERBAIKAN 144');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0730', 'YOPIE BARU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0731', 'KDS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0732', 'NANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0733', 'SPM FASHION DISPLAY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0734', 'DEDE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0735', 'TOKO BERLIAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0736', 'JOHAN ANGGADA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0737', 'JHON KHATAM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0738', 'MAICIN KHATAM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0739', 'CI IYEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0740', 'ANDY PRNT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0741', 'MAGENTA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0742', 'YAYU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0743', 'TWIG HOUSE ( KONSINYASI )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0744', 'UD STYLE/LENNY S');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0745', 'KAYDEE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0746', 'HERLINA K');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0747', 'PT ADETEX');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0748', 'CELLINE SILVER');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0749', 'SYLVIE/JENNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0750', 'C GAMA CLAUDIANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0751', 'MUNDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0752', 'IRWAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0753', 'CANDRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0754', 'I KIKI ( KONSINYASI) 853');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0755', 'SHIAW HUNG ( KONSINYASI )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0756', 'ALDI FASHION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0757', 'NING/SARIMBIT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0758', 'PRIMABEL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0759', 'I KUANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0760', 'SANGWOO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0761', 'P ANDREW');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0762', 'WINS FASHION K');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0763', 'STEVEN K');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0764', 'PT WIWA TEXTILE /UD TEKSTIL BERDIKARI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0765', 'RUDI CEMPAKA 620');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0766', 'KIM IN SOO ( KONSINYASI)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0767', 'PT PRIMA PERAHU A (KONSINYASI)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0768', 'PT PERKASA S.L.K');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0769', 'PT FAMILI KEKAL ABADI ( KONS )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0770', 'SUNARDI SIMANORA ( KONSY )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0771', 'PT GEMILANG INTI LESTARINDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0772', 'CV BATIK MARTA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0773', 'SANGKHIONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0774', 'ARIWARNI ( PT GAYA INDOMODEL)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0775', 'CV KARYA JAYA MANDIRI SAKTI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0776', 'ANIMALE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0777', 'FANNEKE (KONSY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0778', 'NADIRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0779', 'KIKI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0780', 'ACING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0781', 'PT BATU KARAS/LILIAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0782', 'ANITA TEA ( KONSY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0783', 'JE T AIME/LINNA EFERINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0784', 'BENNY T (KONSY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0785', 'SPEX SYMBOL /DANAR DONO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0786', 'UD JAYA UTAMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0787', 'TEGUH /YOSSANO KONSY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0788', 'WILLIAM KONSY (WS)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0789', 'ANDY LUKMAN KONS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0790', 'KUMALA JAKARTA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0791', 'SURYA INDAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0792', 'PT FAMILI KEKAL ABADI (KONY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0793', 'JEANY (KONSY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0794', 'TK MODO /I YENNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0795', 'ANTON BCA (KONSY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0796', 'BPK KOSWARA/KONSY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0797', 'I KIKI ACC U/PROPERTY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0798', 'P ALVIN (RELAXOGY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0799', 'I KIKI 2 ( KONSY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0800', 'BAKRIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0801', 'ANDRI CIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0802', 'SUPLER MIX GRD A');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0803', 'JAJAT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0804', 'LENI (KONSYINYASI)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0805', 'KETUT KRISBIANTORO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0806', 'PT CAS WASHING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0807', 'HENDRA/DINAMIS GARMENT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0808', 'IVANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0809', 'ASIONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0810', 'DJ BUSANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0811', 'PT PINNACLE APPARELS/NORTWEST');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0812', '3 KYUNG SEUNG/DASUM MULYADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0813', 'SUKSES HAMINDO SEJAHTERA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0814', '"I KIKI GMT 361');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0815', 'HIDAYAT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0816', 'SARI KADARUSMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0817', 'PT CAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0818', 'BLESSING/JERRY KEMANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0819', 'EDY HANGER');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0820', 'PT MAKMUR  INTERPACK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0821', 'PT DARUL HIJRAH /HJ AYI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0822', 'MR. RAJU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0823', 'YULI BORDIR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0824', 'BUDI JKT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0825', 'MAISIR 906');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0826', 'GUNAWAN BARU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0827', 'HENI YULIANA (DESSY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0828', 'NURDIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0829', 'H. RAMLI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0830', 'INDRA CEMPAKA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0831', 'PT FOREVER GARMINDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0832', 'RACHEL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0833', '"BUDI CIBUBUR 760');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0834', 'BUYUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0835', 'SANTU RAJUT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0836', 'GRACE CHRISTIANI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0837', 'PT GA/MAYOR JUN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0838', 'JHON UCOK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0839', 'IBU TINI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0840', 'MUJI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0841', 'MITRA SANDANG ABADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0842', 'ENI PAMULANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0843', 'JUKIUS JUPRIANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0844', 'CATUR MANUNGGAL PERKASA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0845', 'BPK DONA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0846', 'BPK KAMPRET');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0847', 'EVI HADIYANY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0848', 'ERNI SENTUL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0849', 'HAJI HADI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0850', 'TOKO BONEKA M2');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0851', 'JHONY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0852', 'WAWAN KUMIS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0853', 'JATI ENGGAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0854', 'LISA COLLECTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0855', 'MR LEE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0856', 'ROLLA DESIGN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0857', 'MR MANIS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0858', 'SUHANDI 248');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0859', 'SIAN SIAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0860', 'HENDRI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0861', 'HENGKI/MIMI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0862', 'MAISIR 773');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0863', 'BING SURABAYA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0864', 'MJR KAIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0865', 'SELVY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0866', 'ANTON GUNADI/JOKO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0867', 'RAY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0868', 'DELVIN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0869', 'PT BIDAYA/LIVING ROOM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0870', 'TRANSFORM MANEQUINS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0871', 'WAHAN TATA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0872', 'SULISTIONO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0873', 'IYAN/OMOH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0874', 'HERMAN BARU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0875', 'H BENNY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0876', 'CERITA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0877', 'PADDU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0878', 'BEYOST');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0879', 'MESSA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0880', 'PT SHIN WOO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0881', 'ARMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0882', 'MEI LING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0883', 'EKA KARYA/IBU RINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0884', 'HERU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0885', 'TAKUMI/BPK ROY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0886', 'HARRY SOLO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0887', 'SRI SEMARANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0888', 'HERMAN LISNA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0889', 'MR PRAVEEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0890', 'PT SUN JONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0891', 'TINA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0892', 'AMEI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0893', '"H MADI 164');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0894', 'DADANG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0895', 'SUTAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0896', 'DENI/MAJU JAYA GLOBAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0897', 'AMING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0898', 'RUDIANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0899', 'HAPID/ABA STICK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0900', 'HENDRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0901', 'PT GRAHA BUSANA GEMILANG/JAYA SENTOSA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0902', 'IYAN JUNED');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0903', 'PT.PRIMA MENARA UTAMA/HIDAYAT');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0904', 'HASBI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0905', 'PT SAHABAT UNGGUL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0906', 'UDIN SAPUTRA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0907', 'BUDI CARZABETA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0908', 'WILLIAM HERMAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0909', 'SUSANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0910', 'I LIA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0911', 'BANDUNG FO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0912', 'LIVIA LING LING');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0913', 'SUPLIER HADIAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0914', 'PT. Biginusindo Permai');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0915', 'PT. Bumi Pusaka Adhi Perkasa');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0916', 'PT. Karunia Dharma Sejahtera');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0917', 'PT. Cipta Kreasisandang Mandiri');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0918', 'CV. Sunflower');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0919', 'PT. Turangga Kertakencana');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0920', 'CV. Elatindo Kharisma Jaya');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0921', 'PT. Vidiaelok Lestari Garmindo');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0922', 'PT. Berkat Usaha Jaya');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0923', 'PT. Adiwarna Busana Lestari');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0924', 'PT. Ballin Ekalestari');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0925', 'PT. Central Network Indonesia');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0926', 'PT. Citra Crocotama Internasional');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0927', 'PT. Citra Surya Pasific');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0928', 'PT. Bina Busana Internusa');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0929', 'PT. Citra Busana Jaya Pertiwi');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0930', 'PT. Defasindo Kreasi Prima');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0931', 'PT. Harindotama Mandiri');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0932', 'PT. Indonesia Wacoal');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0933', 'PT. Konia Putra Lestari');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0934', 'PT. Mega Indah Pratama');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0935', 'PT. Mega Perintis');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0936', 'PT. Picarinjaya Abadi');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0937', 'PT. Point Mas Cemerlang');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0938', 'PT. Primajaya Pantes Garment');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0939', 'PT. Rodeo Kerta Kencana');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0940', 'PT. Dharmarindo ANugerah Surya');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0941', 'PT. Sumber Kreasi Fumiko');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0942', 'PT. Tri Anugrah Fashion');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0943', 'PT. Joey Sasmita Lencana');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0944', 'PT. Jusindo Sumberprakarsa');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0945', 'PT. Kurnia Astasurya');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0946', 'PT. Rofina Indah Jaya');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0947', 'PT. Trinitas Mulia Abadi');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0948', 'PT.Tritunggal Esa Senanda');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0949', 'PT. Sumber Dipta Asia');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0950', 'PT. Tas Centre Cemerlang');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0951', 'PT. Warna Mardhika');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0952', 'PT. Madonna Variakreasi');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0953', 'STOCK CENTRE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0954', 'PT.AMBASSADOR GARMINDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0955', 'CV.Sinergi Sukses Indonesia');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0956', 'AGUNG KAMDI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0957', 'DAVID PAGARSIH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0958', 'DONI ANGGADA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0959', 'THIRD DAY CLOTHING (ALWIN)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0960', 'CV.SINAR RAYA ABADI (RAY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0961', 'TOHO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0962', 'PRIMA MAKMUR HANGER');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0963', 'BPK. IYUS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0964', 'YUKARI WAHYU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0965', 'AAT ANTON');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0966', 'YURICA (MY JOY)');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0967', 'EPISODE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0968', 'IAN PORIS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0969', 'KENCANA PLASTIK');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0970', 'IBU VONI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0971', 'ARI KHATAM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0972', 'PT STARINDO JAYA UTAMA/IBU II');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0973', 'HUSEIN ANTON');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0974', 'OKI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0975', 'PT PRIMA GRACINDO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0976', 'BANDAR GANTUNGAN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0977', 'INSPORT BONAR ( KONSY )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0978', 'RON 88');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0979', 'CV HARISMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0980', 'BARATA BATIK ( KONSY )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0981', 'CV COLLIN VICTORY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0982', 'CV. KARUNIA TRITUNGGAL ( ALWIN )');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0983', 'PD LAYAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0984', 'LAMONTE.id');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0985', 'ESTHER');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0986', 'JULIANA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0987', 'KO CUCU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0988', 'GHINA SECRET');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0989', 'PT. PERUSAHAAN LOGAM BIMA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0990', 'KO CUCU KONSINYASI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0991', 'RUMAH MODE FO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0992', 'NIBIRU');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0993', 'NURYANTO');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0994', 'ACHEN');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0995', 'YURI/CERITA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0996', 'MR KIM');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0997', 'PD PONDOK TAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0998', 'ILUVA JAYA TAS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('0999', 'IAN / IMPERIAL');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1000', 'HAT VS HEAD');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1001', 'DADANG POLISI');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1002', 'ARKIDS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1003', '267 SHOP');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1004', 'Sis - Ex');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1005', 'BENY CIBINONG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1006', 'PUBLICITY');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1007', 'BRAND REVOLUTION');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1008', 'MINGALA');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1009', 'POOKIE');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1010', 'NESSA SLEEPWEAR');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1011', 'BODY BOSS');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1012', 'BINTANG GAJAH');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1013', 'DUNIA SOUVENIR BANDUNG');
INSERT INTO "public"."suppliers" ("code", "name") VALUES ('1014', 'MAHKOTA KENCANA');
