-- ----------------------------
-- Records of categories
-- ----------------------------
INSERT INTO "public"."categories" VALUES (1, NULL, NULL, '1011', 'MEN | BLAZER');
INSERT INTO "public"."categories" VALUES (2, NULL, NULL, '1012', 'MEN | CARDIGAN');
INSERT INTO "public"."categories" VALUES (3, NULL, NULL, '1013', 'MEN | CLOTHING (mix)');
INSERT INTO "public"."categories" VALUES (4, NULL, NULL, '1014', 'MEN | COAT');
INSERT INTO "public"."categories" VALUES (5, NULL, NULL, '1015', 'MEN | BOARD SHORT');
INSERT INTO "public"."categories" VALUES (6, NULL, NULL, '1016', 'MEN | JACKET');
INSERT INTO "public"."categories" VALUES (7, NULL, NULL, '1017', 'MEN | JAS');
INSERT INTO "public"."categories" VALUES (8, NULL, NULL, '1018', 'MEN | JUMPSUIT');
INSERT INTO "public"."categories" VALUES (9, NULL, NULL, '1019', 'MEN | LONG PANTS');
INSERT INTO "public"."categories" VALUES (10, NULL, NULL, '1020', 'MEN | MOESLEM');
INSERT INTO "public"."categories" VALUES (11, NULL, NULL, '1021', 'MEN | PIJAMAS');
INSERT INTO "public"."categories" VALUES (12, NULL, NULL, '1022', 'MEN | POLO SHIRT');
INSERT INTO "public"."categories" VALUES (13, NULL, NULL, '1023', 'MEN | SAFARI');
INSERT INTO "public"."categories" VALUES (14, NULL, NULL, '1024', 'MEN | SARUNG');
INSERT INTO "public"."categories" VALUES (15, NULL, NULL, '1025', 'MEN | SHIRT');
INSERT INTO "public"."categories" VALUES (16, NULL, NULL, '1026', 'MEN | SHORT PANTS');
INSERT INTO "public"."categories" VALUES (17, NULL, NULL, '1027', 'MEN | SUIT SHIRT');
INSERT INTO "public"."categories" VALUES (18, NULL, NULL, '1028', 'MEN | SWEAT SHIRT');
INSERT INTO "public"."categories" VALUES (19, NULL, NULL, '1029', 'MEN | SWEATER');
INSERT INTO "public"."categories" VALUES (20, NULL, NULL, '1030', 'MEN | SWIMSUIT');
INSERT INTO "public"."categories" VALUES (21, NULL, NULL, '1031', 'MEN | T SHIRT');
INSERT INTO "public"."categories" VALUES (22, NULL, NULL, '1032', 'MEN | TRAVEL BAG');
INSERT INTO "public"."categories" VALUES (23, NULL, NULL, '1033', 'MEN | UNDERWEAR');
INSERT INTO "public"."categories" VALUES (24, NULL, NULL, '1034', 'MEN | VEST');
INSERT INTO "public"."categories" VALUES (25, NULL, NULL, '1035', 'MEN | WAIST BAG');
INSERT INTO "public"."categories" VALUES (26, NULL, NULL, '1036', 'MEN | SPORT');
INSERT INTO "public"."categories" VALUES (27, NULL, NULL, '1037', 'MEN | CLOTHES SUIT');
INSERT INTO "public"."categories" VALUES (28, NULL, NULL, '1038', 'MEN | CLOTHING SPORT');
INSERT INTO "public"."categories" VALUES (29, NULL, NULL, '1101', 'LADIES | AEROBIC SUIT');
INSERT INTO "public"."categories" VALUES (30, NULL, NULL, '1102', 'LADIES | BLAZER');
INSERT INTO "public"."categories" VALUES (31, NULL, NULL, '1103', 'LADIES | BLOUSE');
INSERT INTO "public"."categories" VALUES (32, NULL, NULL, '1104', 'LADIES | BRA');
INSERT INTO "public"."categories" VALUES (33, NULL, NULL, '1105', 'LADIES | CARDIGAN');
INSERT INTO "public"."categories" VALUES (34, NULL, NULL, '1106', 'LADIES | CLOTHES SPORT');
INSERT INTO "public"."categories" VALUES (35, NULL, NULL, '1107', 'LADIES | CLOTHES SUIT');
INSERT INTO "public"."categories" VALUES (36, NULL, NULL, '1108', 'LADIES | CLOTHING (mix)');
INSERT INTO "public"."categories" VALUES (37, NULL, NULL, '1109', 'LADIES | CLOTHING SPORT');
INSERT INTO "public"."categories" VALUES (38, NULL, NULL, '1110', 'LADIES | COAT');
INSERT INTO "public"."categories" VALUES (39, NULL, NULL, '1111', 'LADIES | CROP TOP');
INSERT INTO "public"."categories" VALUES (40, NULL, NULL, '1112', 'LADIES | DRESS');
INSERT INTO "public"."categories" VALUES (41, NULL, NULL, '1113', 'LADIES | GAMIS');
INSERT INTO "public"."categories" VALUES (42, NULL, NULL, '1114', 'LADIES | HOODIES');
INSERT INTO "public"."categories" VALUES (43, NULL, NULL, '1115', 'LADIES | HOT PANTS');
INSERT INTO "public"."categories" VALUES (44, NULL, NULL, '1116', 'LADIES | JACKET');
INSERT INTO "public"."categories" VALUES (45, NULL, NULL, '1117', 'LADIES | JUMPSUIT');
INSERT INTO "public"."categories" VALUES (46, NULL, NULL, '1118', 'LADIES | KIMONO');
INSERT INTO "public"."categories" VALUES (47, NULL, NULL, '1119', 'LADIES | LEGGING');
INSERT INTO "public"."categories" VALUES (48, NULL, NULL, '1120', 'LADIES | LONG DRESS');
INSERT INTO "public"."categories" VALUES (49, NULL, NULL, '1121', 'LADIES | LONG PANTS');
INSERT INTO "public"."categories" VALUES (50, NULL, NULL, '1122', 'LADIES | MOESLEM');
INSERT INTO "public"."categories" VALUES (51, NULL, NULL, '1123', 'LADIES | PIJAMAS');
INSERT INTO "public"."categories" VALUES (52, NULL, NULL, '1124', 'LADIES | POLO SHIRT');
INSERT INTO "public"."categories" VALUES (53, NULL, NULL, '1125', 'LADIES | SHIRT');
INSERT INTO "public"."categories" VALUES (54, NULL, NULL, '1126', 'LADIES | SHORT PANTS');
INSERT INTO "public"."categories" VALUES (55, NULL, NULL, '1127', 'LADIES | SKIRT');
INSERT INTO "public"."categories" VALUES (56, NULL, NULL, '1128', 'LADIES | SKORT');
INSERT INTO "public"."categories" VALUES (57, NULL, NULL, '1129', 'LADIES | SUIT SHIRT');
INSERT INTO "public"."categories" VALUES (58, NULL, NULL, '1130', 'LADIES | SWEAT SHIRT');
INSERT INTO "public"."categories" VALUES (59, NULL, NULL, '1131', 'LADIES | SWEATER');
INSERT INTO "public"."categories" VALUES (60, NULL, NULL, '1132', 'LADIES | SWIMSUIT');
INSERT INTO "public"."categories" VALUES (61, NULL, NULL, '1133', 'LADIES | T SHIRT');
INSERT INTO "public"."categories" VALUES (62, NULL, NULL, '1134', 'LADIES | TANK TOP');
INSERT INTO "public"."categories" VALUES (63, NULL, NULL, '1135', 'LADIES | UNDERWEAR');
INSERT INTO "public"."categories" VALUES (64, NULL, NULL, '1136', 'LADIES | VEST');
INSERT INTO "public"."categories" VALUES (65, NULL, NULL, '1137', 'LADIES | WAIST BAG');
INSERT INTO "public"."categories" VALUES (66, NULL, NULL, '1138', 'LADIES | KAIN BATIK');
INSERT INTO "public"."categories" VALUES (67, NULL, NULL, '1139', 'LADIES | PONCHO');
INSERT INTO "public"."categories" VALUES (68, NULL, NULL, '1201', 'KIDS | AEROBIC SUIT');
INSERT INTO "public"."categories" VALUES (69, NULL, NULL, '1202', 'KIDS | BLOUSE');
INSERT INTO "public"."categories" VALUES (70, NULL, NULL, '1203', 'KIDS | BRA');
INSERT INTO "public"."categories" VALUES (71, NULL, NULL, '1204', 'KIDS | CARDIGAN');
INSERT INTO "public"."categories" VALUES (72, NULL, NULL, '1205', 'KIDS | CLOTHES SPORT');
INSERT INTO "public"."categories" VALUES (73, NULL, NULL, '1206', 'KIDS | CLOTHES SUIT');
INSERT INTO "public"."categories" VALUES (74, NULL, NULL, '1207', 'KIDS | CLOTHING (mix)');
INSERT INTO "public"."categories" VALUES (75, NULL, NULL, '1208', 'KIDS | CLOTHING SPORT');
INSERT INTO "public"."categories" VALUES (76, NULL, NULL, '1209', 'KIDS | COAT');
INSERT INTO "public"."categories" VALUES (77, NULL, NULL, '1210', 'KIDS | CROP TOP');
INSERT INTO "public"."categories" VALUES (78, NULL, NULL, '1211', 'KIDS | DRESS');
INSERT INTO "public"."categories" VALUES (79, NULL, NULL, '1212', 'KIDS | HOODIES');
INSERT INTO "public"."categories" VALUES (80, NULL, NULL, '1213', 'KIDS | HOT PANTS');
INSERT INTO "public"."categories" VALUES (81, NULL, NULL, '1214', 'KIDS | JACKET');
INSERT INTO "public"."categories" VALUES (82, NULL, NULL, '1215', 'KIDS | JUMPSUIT');
INSERT INTO "public"."categories" VALUES (83, NULL, NULL, '1216', 'KIDS | KIMONO');
INSERT INTO "public"."categories" VALUES (84, NULL, NULL, '1217', 'KIDS | LEGGING');
INSERT INTO "public"."categories" VALUES (85, NULL, NULL, '1218', 'KIDS | LONG PANTS');
INSERT INTO "public"."categories" VALUES (86, NULL, NULL, '1219', 'KIDS | MOESLEM');
INSERT INTO "public"."categories" VALUES (87, NULL, NULL, '1220', 'KIDS | PIJAMAS');
INSERT INTO "public"."categories" VALUES (88, NULL, NULL, '1221', 'KIDS | POLO SHIRT');
INSERT INTO "public"."categories" VALUES (89, NULL, NULL, '1222', 'KIDS | SHIRT');
INSERT INTO "public"."categories" VALUES (90, NULL, NULL, '1223', 'KIDS | SHORT PANT');
INSERT INTO "public"."categories" VALUES (91, NULL, NULL, '1224', 'KIDS | SHORT PANTS');
INSERT INTO "public"."categories" VALUES (92, NULL, NULL, '1225', 'KIDS | SKIRT');
INSERT INTO "public"."categories" VALUES (93, NULL, NULL, '1226', 'KIDS | SKORT');
INSERT INTO "public"."categories" VALUES (94, NULL, NULL, '1227', 'KIDS | SLING BAG');
INSERT INTO "public"."categories" VALUES (95, NULL, NULL, '1228', 'KIDS | SUIT');
INSERT INTO "public"."categories" VALUES (96, NULL, NULL, '1229', 'KIDS | SUIT SHIRT');
INSERT INTO "public"."categories" VALUES (97, NULL, NULL, '1230', 'KIDS | SWEAT SHIRT');
INSERT INTO "public"."categories" VALUES (98, NULL, NULL, '1231', 'KIDS | SWEATER');
INSERT INTO "public"."categories" VALUES (99, NULL, NULL, '1232', 'KIDS | SWIMSUIT');
INSERT INTO "public"."categories" VALUES (100, NULL, NULL, '1233', 'KIDS | T SHIRT');
INSERT INTO "public"."categories" VALUES (101, NULL, NULL, '1234', 'KIDS | TANK TOP');
INSERT INTO "public"."categories" VALUES (102, NULL, NULL, '1235', 'KIDS | UNDERWEAR');
INSERT INTO "public"."categories" VALUES (103, NULL, NULL, '1236', 'KIDS | VEST');
INSERT INTO "public"."categories" VALUES (104, NULL, NULL, '1237', 'KIDS | WAIST BAG');
INSERT INTO "public"."categories" VALUES (105, NULL, NULL, '1238', 'KIDS | JAS');
INSERT INTO "public"."categories" VALUES (106, NULL, NULL, '1239', 'KIDS | LONG JOHN');
INSERT INTO "public"."categories" VALUES (107, NULL, NULL, '1240', 'KIDS | PONCHO');
INSERT INTO "public"."categories" VALUES (108, NULL, NULL, '1241', 'KIDS | JUMPER');
INSERT INTO "public"."categories" VALUES (109, NULL, NULL, '1301', 'BAG n SHOES | BACK PACK');
INSERT INTO "public"."categories" VALUES (110, NULL, NULL, '1302', 'BAG n SHOES | HAND BAG');
INSERT INTO "public"."categories" VALUES (111, NULL, NULL, '1303', 'BAG n SHOES | SHOES');
INSERT INTO "public"."categories" VALUES (112, NULL, NULL, '1304', 'BAG n SHOES | SLING BAG');
INSERT INTO "public"."categories" VALUES (113, NULL, NULL, '1305', 'BAG n SHOES | SLIPPER');
INSERT INTO "public"."categories" VALUES (114, NULL, NULL, '1306', 'BAG n SHOES | TRAVEL BAG');
INSERT INTO "public"."categories" VALUES (115, NULL, NULL, '1307', 'BAG n SHOES | WAIST BAG');
INSERT INTO "public"."categories" VALUES (116, NULL, NULL, '1308', 'BAG n SHOES | BAG');
INSERT INTO "public"."categories" VALUES (117, NULL, NULL, '1309', 'BAG n SHOES | CHEST BAG');
INSERT INTO "public"."categories" VALUES (118, NULL, NULL, '1310', 'BAG n SHOES | BUM BAG');
INSERT INTO "public"."categories" VALUES (119, NULL, NULL, '1311', 'BAG n SHOES | BEAUTY CASE BAG');
INSERT INTO "public"."categories" VALUES (120, NULL, NULL, '1401', 'ACCESSORIES | BANDO');
INSERT INTO "public"."categories" VALUES (121, NULL, NULL, '1402', 'ACCESSORIES | BELT');
INSERT INTO "public"."categories" VALUES (122, NULL, NULL, '1403', 'ACCESSORIES | BROS');
INSERT INTO "public"."categories" VALUES (123, NULL, NULL, '1404', 'ACCESSORIES | EAR CAP');
INSERT INTO "public"."categories" VALUES (124, NULL, NULL, '1405', 'ACCESSORIES | GLOVES');
INSERT INTO "public"."categories" VALUES (125, NULL, NULL, '1406', 'ACCESSORIES | HAIRBANDS');
INSERT INTO "public"."categories" VALUES (126, NULL, NULL, '1407', 'ACCESSORIES | HAND GLOVES');
INSERT INTO "public"."categories" VALUES (127, NULL, NULL, '1408', 'ACCESSORIES | HAT');
INSERT INTO "public"."categories" VALUES (128, NULL, NULL, '1409', 'ACCESSORIES | SCARFT');
INSERT INTO "public"."categories" VALUES (129, NULL, NULL, '1410', 'ACCESSORIES | SKULLCAPS');
INSERT INTO "public"."categories" VALUES (130, NULL, NULL, '1411', 'ACCESSORIES | SOCKS');
INSERT INTO "public"."categories" VALUES (131, NULL, NULL, '1412', 'ACCESSORIES | SWIMSUIT');
INSERT INTO "public"."categories" VALUES (132, NULL, NULL, '1413', 'ACCESSORIES | SYAL');
INSERT INTO "public"."categories" VALUES (133, NULL, NULL, '1414', 'ACCESSORIES | TIE');
INSERT INTO "public"."categories" VALUES (134, NULL, NULL, '1415', 'ACCESSORIES | TOWEL');
INSERT INTO "public"."categories" VALUES (135, NULL, NULL, '1416', 'ACCESSORIES | WALLET');
INSERT INTO "public"."categories" VALUES (136, NULL, NULL, '1417', 'ACCESSORIES | SUN GLASSES');
INSERT INTO "public"."categories" VALUES (137, NULL, NULL, '1418', 'ACCESSORIES | FASHION WINGS');
INSERT INTO "public"."categories" VALUES (138, NULL, NULL, '1419', 'ACCESSORIES | PIN');
INSERT INTO "public"."categories" VALUES (139, NULL, NULL, '1420', 'ACCESSORIES | BUFF');
INSERT INTO "public"."categories" VALUES (140, NULL, NULL, '1421', 'ACCESSORIES | test data');
INSERT INTO "public"."categories" VALUES (141, NULL, NULL, '1422', 'ACCESSORIES | TALI HP');
INSERT INTO "public"."categories" VALUES (142, NULL, NULL, '1423', 'ACCESSORIES | BAG CHARM');
INSERT INTO "public"."categories" VALUES (143, NULL, NULL, '1501', 'TOYS n VIDEO GAME | DOLLS');
INSERT INTO "public"."categories" VALUES (144, NULL, NULL, '1601', 'BATH | BLANKET');
INSERT INTO "public"."categories" VALUES (145, NULL, NULL, '1602', 'BATH | MAT');
INSERT INTO "public"."categories" VALUES (146, NULL, NULL, '1603', 'BATH | TOWEL');
INSERT INTO "public"."categories" VALUES (147, NULL, NULL, '1604', 'BATH | UMBRELLA');
INSERT INTO "public"."categories" VALUES (148, NULL, NULL, '1605', 'BATH | BATH ACCESORIES');
INSERT INTO "public"."categories" VALUES (149, NULL, NULL, '1606', 'BATH | HANDKERCHIEF');
INSERT INTO "public"."categories" VALUES (150, NULL, NULL, '1701', 'MOESLEM | VEIL');
INSERT INTO "public"."categories" VALUES (151, NULL, NULL, '1702', 'MOESLEM | PRAYER RUGS');
INSERT INTO "public"."categories" VALUES (152, NULL, NULL, '1801', 'FITNESS AND OUTDOOR');
INSERT INTO "public"."categories" VALUES (153, NULL, NULL, '1901', 'OUTERWEAR | COAT');
INSERT INTO "public"."categories" VALUES (154, NULL, NULL, '1902', 'OUTERWEAR | RAIN COAT');
INSERT INTO "public"."categories" VALUES (155, NULL, NULL, '2001', 'SUPPLY | PLASTIC BAG');
INSERT INTO "public"."categories" VALUES (156, NULL, NULL, '2002', 'SUPPLY | PROMOTION GOODS');
INSERT INTO "public"."categories" VALUES (157, NULL, NULL, '2003', 'SUPPLY | WRAPING PAPER');
INSERT INTO "public"."categories" VALUES (158, NULL, NULL, '2004', 'SUPPLY | PAPER BAG');
INSERT INTO "public"."categories" VALUES (159, NULL, NULL, '2005', 'SUPPLY | SHOPPING BAG');
INSERT INTO "public"."categories" VALUES (160, NULL, NULL, '2101', 'NON TRADE | COMPUTER');
INSERT INTO "public"."categories" VALUES (161, NULL, NULL, '2102', 'NON TRADE | LABEL n TAG');
INSERT INTO "public"."categories" VALUES (162, NULL, NULL, '2103', 'NON TRADE | PRINTER BARCODE');
INSERT INTO "public"."categories" VALUES (163, NULL, NULL, '2201', 'OPEN CODE | OPEN CODE');
INSERT INTO "public"."categories" VALUES (164, NULL, NULL, '2202', 'OPEN CODE | SERVICES');
INSERT INTO "public"."categories" VALUES (165, NULL, NULL, '2301', 'HAIR ACCESSORY | BANDANA');
INSERT INTO "public"."categories" VALUES (166, NULL, NULL, '2302', 'HAIR ACCESSORY | BANDO');
INSERT INTO "public"."categories" VALUES (167, NULL, NULL, '2303', 'HAIR ACCESSORY | BROS');
INSERT INTO "public"."categories" VALUES (168, NULL, NULL, '2304', 'HAIR ACCESSORY | COMB');
INSERT INTO "public"."categories" VALUES (169, NULL, NULL, '2305', 'HAIR ACCESSORY | HAIRBANDS');
INSERT INTO "public"."categories" VALUES (170, NULL, NULL, '2306', 'HAIR ACCESSORY | TIE THE VEIL');
INSERT INTO "public"."categories" VALUES (171, NULL, NULL, '2307', 'HAIR ACCESSORY | TOOLS');
INSERT INTO "public"."categories" VALUES (172, NULL, NULL, '2308', 'HAIR ACCESSORY | WALLET');
INSERT INTO "public"."categories" VALUES (173, NULL, NULL, '2401', 'JEWELRY | BRACELET');
INSERT INTO "public"."categories" VALUES (174, NULL, NULL, '2402', 'JEWELRY | NECKLACE');
INSERT INTO "public"."categories" VALUES (175, NULL, NULL, '2403', 'JEWELRY | RING');
INSERT INTO "public"."categories" VALUES (176, NULL, NULL, '2501', 'PERSONAL ACCESSORY | KEY CHAIN');
INSERT INTO "public"."categories" VALUES (177, NULL, NULL, '2601', 'JEWELRY | EARRINGS');
INSERT INTO "public"."categories" VALUES (178, NULL, NULL, '2701', 'BEAUTY TOOLS n ACCESSORIES | TOOLS');
INSERT INTO "public"."categories" VALUES (179, NULL, NULL, '2702', 'BEAUTY TOOLS n ACCESSORIES | SPONGE');
INSERT INTO "public"."categories" VALUES (180, NULL, NULL, '2703', 'BEAUTY TOOLS n ACCESSORIES | HAIR ACCESORIES');
INSERT INTO "public"."categories" VALUES (181, NULL, NULL, '2704', 'BEAUTY TOOLS n ACCESSORIES | NAIL ACCESSORIES');
INSERT INTO "public"."categories" VALUES (182, NULL, NULL, '2801', 'NON FASHION | MINERAL WATER');
INSERT INTO "public"."categories" VALUES (183, NULL, NULL, '2802', 'NON FASHION | PLASTIC EQUIPMENT');
INSERT INTO "public"."categories" VALUES (184, NULL, NULL, '2803', 'NON FASHION | HANDPHONE ACCESSORIES');
INSERT INTO "public"."categories" VALUES (185, NULL, NULL, '2804', 'NON FASHION | STATIONERY');
INSERT INTO "public"."categories" VALUES (186, NULL, NULL, '2805', 'NON FASHION | LUNCH BOX');
INSERT INTO "public"."categories" VALUES (187, NULL, NULL, '2806', 'NON FASHION | TISSUE BOX');
INSERT INTO "public"."categories" VALUES (188, NULL, NULL, '2807', 'NON FASHION | PHOTO ALMBUM');
INSERT INTO "public"."categories" VALUES (189, NULL, NULL, '2808', 'NON FASHION | BOOKS');
INSERT INTO "public"."categories" VALUES (190, NULL, NULL, '2809', 'NON FASHION | MEDICAL PLASTER');
INSERT INTO "public"."categories" VALUES (191, NULL, NULL, '2810', 'NON FASHION | PIN');
INSERT INTO "public"."categories" VALUES (192, NULL, NULL, '2811', 'NON FASHION | FOOD');
INSERT INTO "public"."categories" VALUES (193, NULL, NULL, '2812', 'NON FASHION | CARD BOX');
INSERT INTO "public"."categories" VALUES (194, NULL, NULL, '2813', 'NON FASHION | HOUSEHOLD');
INSERT INTO "public"."categories" VALUES (195, NULL, NULL, '2814', 'NON FASHION | GLASSES CASE');
INSERT INTO "public"."categories" VALUES (196, NULL, NULL, '2815', 'NON FASHION | PELAMPUNG');
INSERT INTO "public"."categories" VALUES (197, NULL, NULL, '2901', 'CLOTHING MIX | CLOTHING MIX');
