-- ----------------------------
-- Records of suppliers
-- ----------------------------
INSERT INTO "public"."suppliers" VALUES (1, NULL, NULL, '0000', 'Supplier Umum');
INSERT INTO "public"."suppliers" VALUES (2, NULL, NULL, '0001', 'PT. Blesindo Mega Anugerah');
INSERT INTO "public"."suppliers" VALUES (3, NULL, NULL, '0002', 'APANG/PT. SEJAHTERA');
INSERT INTO "public"."suppliers" VALUES (4, NULL, NULL, '0003', 'DELAMI');
INSERT INTO "public"."suppliers" VALUES (5, NULL, NULL, '0004', 'MIMING');
INSERT INTO "public"."suppliers" VALUES (6, NULL, NULL, '0005', 'PT MULYA LESTARI');
INSERT INTO "public"."suppliers" VALUES (7, NULL, NULL, '0006', 'LINK STOCK-EDDY HANGER');
INSERT INTO "public"."suppliers" VALUES (8, NULL, NULL, '0007', 'ISHAK');
INSERT INTO "public"."suppliers" VALUES (9, NULL, NULL, '0008', 'TATANG');
INSERT INTO "public"."suppliers" VALUES (10, NULL, NULL, '0009', 'LELLY');
INSERT INTO "public"."suppliers" VALUES (11, NULL, NULL, '0010', 'PT DAEHAN GLOBAL');
INSERT INTO "public"."suppliers" VALUES (12, NULL, NULL, '0011', 'NOVA COLL/SUWARDI');
INSERT INTO "public"."suppliers" VALUES (13, NULL, NULL, '0012', 'CHRISTIANTO');
INSERT INTO "public"."suppliers" VALUES (14, NULL, NULL, '0013', 'METRO EXIM');
INSERT INTO "public"."suppliers" VALUES (15, NULL, NULL, '0014', 'TRI PRIMA');
INSERT INTO "public"."suppliers" VALUES (16, NULL, NULL, '0015', 'SHERLY/YENI');
INSERT INTO "public"."suppliers" VALUES (17, NULL, NULL, '0016', 'MAHKOTA KENCANA/LINA');
INSERT INTO "public"."suppliers" VALUES (18, NULL, NULL, '0017', 'LITA');
INSERT INTO "public"."suppliers" VALUES (19, NULL, NULL, '0018', 'FERRY');
INSERT INTO "public"."suppliers" VALUES (20, NULL, NULL, '0019', 'MISS PARK');
INSERT INTO "public"."suppliers" VALUES (21, NULL, NULL, '0020', 'IRENE');
INSERT INTO "public"."suppliers" VALUES (22, NULL, NULL, '0021', 'AGUS');
INSERT INTO "public"."suppliers" VALUES (23, NULL, NULL, '0022', 'HANY/DADY');
INSERT INTO "public"."suppliers" VALUES (24, NULL, NULL, '0023', 'AKIUN (WISH COLLECTION)');
INSERT INTO "public"."suppliers" VALUES (25, NULL, NULL, '0024', 'SUZANNA');
INSERT INTO "public"."suppliers" VALUES (26, NULL, NULL, '0025', 'CECILIA SARJONO');
INSERT INTO "public"."suppliers" VALUES (27, NULL, NULL, '0026', 'PETRUS/PUSAT EXPORT');
INSERT INTO "public"."suppliers" VALUES (28, NULL, NULL, '0027', 'SANDY');
INSERT INTO "public"."suppliers" VALUES (29, NULL, NULL, '0028', 'YULIUS/CAROLINE II');
INSERT INTO "public"."suppliers" VALUES (30, NULL, NULL, '0029', 'LENNY SUTANDI');
INSERT INTO "public"."suppliers" VALUES (31, NULL, NULL, '0030', 'YOSSY');
INSERT INTO "public"."suppliers" VALUES (32, NULL, NULL, '0031', 'IKUANG/ITINK');
INSERT INTO "public"."suppliers" VALUES (33, NULL, NULL, '0032', 'TANTI(636)');
INSERT INTO "public"."suppliers" VALUES (34, NULL, NULL, '0033', 'DANI/M RAMDHAN');
INSERT INTO "public"."suppliers" VALUES (35, NULL, NULL, '0034', 'BERNADETTE NATALIA/PT SINAR MATAHARI');
INSERT INTO "public"."suppliers" VALUES (36, NULL, NULL, '0035', 'PT DINEXINDO/ADI KARYA');
INSERT INTO "public"."suppliers" VALUES (37, NULL, NULL, '0036', 'KWIENG');
INSERT INTO "public"."suppliers" VALUES (38, NULL, NULL, '0037', 'PT INKORDAN');
INSERT INTO "public"."suppliers" VALUES (39, NULL, NULL, '0038', 'NANA CLT');
INSERT INTO "public"."suppliers" VALUES (40, NULL, NULL, '0039', 'LIVIA WINARDI');
INSERT INTO "public"."suppliers" VALUES (41, NULL, NULL, '0040', 'BERNARD');
INSERT INTO "public"."suppliers" VALUES (42, NULL, NULL, '0041', 'LENI SUGIRI');
INSERT INTO "public"."suppliers" VALUES (43, NULL, NULL, '0042', 'BUDIYANTO MULYANA');
INSERT INTO "public"."suppliers" VALUES (44, NULL, NULL, '0043', 'HENRY/RUDY');
INSERT INTO "public"."suppliers" VALUES (45, NULL, NULL, '0044', 'NANA COLECTION');
INSERT INTO "public"."suppliers" VALUES (46, NULL, NULL, '0045', 'AK GARMENT /ASHOK K. H');
INSERT INTO "public"."suppliers" VALUES (47, NULL, NULL, '0046', 'ANSYE');
INSERT INTO "public"."suppliers" VALUES (48, NULL, NULL, '0047', 'VIVALDI');
INSERT INTO "public"."suppliers" VALUES (49, NULL, NULL, '0048', 'YANDI');
INSERT INTO "public"."suppliers" VALUES (50, NULL, NULL, '0049', 'DARUSMAN');
INSERT INTO "public"."suppliers" VALUES (51, NULL, NULL, '0050', 'SANNY');
INSERT INTO "public"."suppliers" VALUES (52, NULL, NULL, '0051', 'CV PERSADA');
INSERT INTO "public"."suppliers" VALUES (53, NULL, NULL, '0052', 'IIS');
INSERT INTO "public"."suppliers" VALUES (54, NULL, NULL, '0053', 'SATRINDO GARMENT');
INSERT INTO "public"."suppliers" VALUES (55, NULL, NULL, '0054', 'POPO');
INSERT INTO "public"."suppliers" VALUES (56, NULL, NULL, '0055', 'PT COCA COLA');
INSERT INTO "public"."suppliers" VALUES (57, NULL, NULL, '0056', 'USIN');
INSERT INTO "public"."suppliers" VALUES (58, NULL, NULL, '0057', 'CARSONO CIBUBUR');
INSERT INTO "public"."suppliers" VALUES (59, NULL, NULL, '0058', 'HARTONO LILY');
INSERT INTO "public"."suppliers" VALUES (60, NULL, NULL, '0059', 'LOREN FASHION');
INSERT INTO "public"."suppliers" VALUES (61, NULL, NULL, '0060', 'CYBY CITRA BUSANA');
INSERT INTO "public"."suppliers" VALUES (62, NULL, NULL, '0061', 'MR KIM SENTUL');
INSERT INTO "public"."suppliers" VALUES (63, NULL, NULL, '0062', 'ADE FEZA');
INSERT INTO "public"."suppliers" VALUES (64, NULL, NULL, '0063', 'BAHARI');
INSERT INTO "public"."suppliers" VALUES (65, NULL, NULL, '0064', 'SINGAPORE');
INSERT INTO "public"."suppliers" VALUES (66, NULL, NULL, '0065', 'ELISABET/BUYUNG');
INSERT INTO "public"."suppliers" VALUES (67, NULL, NULL, '0066', 'NENI');
INSERT INTO "public"."suppliers" VALUES (68, NULL, NULL, '0067', 'PT JABA GARMINDO');
INSERT INTO "public"."suppliers" VALUES (69, NULL, NULL, '0068', 'KOKEM');
INSERT INTO "public"."suppliers" VALUES (70, NULL, NULL, '0069', 'H KUSNADI');
INSERT INTO "public"."suppliers" VALUES (71, NULL, NULL, '0070', 'NINA');
INSERT INTO "public"."suppliers" VALUES (72, NULL, NULL, '0071', 'INDRA');
INSERT INTO "public"."suppliers" VALUES (73, NULL, NULL, '0072', 'BUSANA IDOLA');
INSERT INTO "public"."suppliers" VALUES (74, NULL, NULL, '0073', 'DENNY');
INSERT INTO "public"."suppliers" VALUES (75, NULL, NULL, '0074', 'YONA/VISANZA/TJONG SING SIANG');
INSERT INTO "public"."suppliers" VALUES (76, NULL, NULL, '0075', 'PT SAMANTRA');
INSERT INTO "public"."suppliers" VALUES (77, NULL, NULL, '0076', 'BIRGITA');
INSERT INTO "public"."suppliers" VALUES (78, NULL, NULL, '0077', 'HELVI');
INSERT INTO "public"."suppliers" VALUES (79, NULL, NULL, '0078', 'ICAY/ANDY/IHING');
INSERT INTO "public"."suppliers" VALUES (80, NULL, NULL, '0079', 'BUDI');
INSERT INTO "public"."suppliers" VALUES (81, NULL, NULL, '0080', 'MUHAMAD AHMAD 082');
INSERT INTO "public"."suppliers" VALUES (82, NULL, NULL, '0081', 'MIMI/INDOCITRA BUSANA /CANCAN');
INSERT INTO "public"."suppliers" VALUES (83, NULL, NULL, '0082', 'MIKE');
INSERT INTO "public"."suppliers" VALUES (84, NULL, NULL, '0083', 'BENNY PRECCY');
INSERT INTO "public"."suppliers" VALUES (85, NULL, NULL, '0084', 'PT LESTARI SANTIKA');
INSERT INTO "public"."suppliers" VALUES (86, NULL, NULL, '0085', 'FENTY');
INSERT INTO "public"."suppliers" VALUES (87, NULL, NULL, '0086', 'PT INDUSTRI INDAH JAYA');
INSERT INTO "public"."suppliers" VALUES (88, NULL, NULL, '0087', 'DONI MAGA');
INSERT INTO "public"."suppliers" VALUES (89, NULL, NULL, '0088', 'DANIEL TJANDRA');
INSERT INTO "public"."suppliers" VALUES (90, NULL, NULL, '0089', 'LING-LING 11');
INSERT INTO "public"."suppliers" VALUES (91, NULL, NULL, '0090', 'SALUM');
INSERT INTO "public"."suppliers" VALUES (92, NULL, NULL, '0091', 'HERMAWAN');
INSERT INTO "public"."suppliers" VALUES (93, NULL, NULL, '0092', 'HILTON');
INSERT INTO "public"."suppliers" VALUES (94, NULL, NULL, '0093', 'BUSUR MAS');
INSERT INTO "public"."suppliers" VALUES (95, NULL, NULL, '0094', 'ERNY');
INSERT INTO "public"."suppliers" VALUES (96, NULL, NULL, '0095', 'ROMMY');
INSERT INTO "public"."suppliers" VALUES (97, NULL, NULL, '0096', 'FIT-U');
INSERT INTO "public"."suppliers" VALUES (98, NULL, NULL, '0097', 'SINTA');
INSERT INTO "public"."suppliers" VALUES (99, NULL, NULL, '0098', 'ADRIANUS (AA)');
INSERT INTO "public"."suppliers" VALUES (100, NULL, NULL, '0099', 'PT BPG');
INSERT INTO "public"."suppliers" VALUES (101, NULL, NULL, '0100', 'HARRY GUNAWAM');
INSERT INTO "public"."suppliers" VALUES (102, NULL, NULL, '0101', 'YANA');
INSERT INTO "public"."suppliers" VALUES (103, NULL, NULL, '0102', 'WILLFRED');
INSERT INTO "public"."suppliers" VALUES (104, NULL, NULL, '0103', 'IVAN/ENNY');
INSERT INTO "public"."suppliers" VALUES (105, NULL, NULL, '0104', 'IYAN HARDIANSYAH');
INSERT INTO "public"."suppliers" VALUES (106, NULL, NULL, '0105', 'GITA W');
INSERT INTO "public"."suppliers" VALUES (107, NULL, NULL, '0106', 'INDAH JAYA DOMPET(HEINCE)');
INSERT INTO "public"."suppliers" VALUES (108, NULL, NULL, '0107', 'M JOHAN(201');
INSERT INTO "public"."suppliers" VALUES (109, NULL, NULL, '0108', 'FREDDY TURANGAN');
INSERT INTO "public"."suppliers" VALUES (110, NULL, NULL, '0109', 'LAURENT');
INSERT INTO "public"."suppliers" VALUES (111, NULL, NULL, '0110', 'AKIONG/HOWTEN');
INSERT INTO "public"."suppliers" VALUES (112, NULL, NULL, '0111', 'PAULUS CANDRA');
INSERT INTO "public"."suppliers" VALUES (113, NULL, NULL, '0112', 'RAJA KAOS');
INSERT INTO "public"."suppliers" VALUES (114, NULL, NULL, '0113', 'SUSI CARLA/FAJAR TERANG ABADI');
INSERT INTO "public"."suppliers" VALUES (115, NULL, NULL, '0114', 'TRIMANDIRI');
INSERT INTO "public"."suppliers" VALUES (116, NULL, NULL, '0115', 'LENNY PANDU');
INSERT INTO "public"."suppliers" VALUES (117, NULL, NULL, '0116', 'PT. PRIMA PERAHU AGUNG/CLN');
INSERT INTO "public"."suppliers" VALUES (118, NULL, NULL, '0117', 'SENDJAJA GUNAWAN');
INSERT INTO "public"."suppliers" VALUES (119, NULL, NULL, '0118', 'SUWARNO');
INSERT INTO "public"."suppliers" VALUES (120, NULL, NULL, '0119', 'ANDRI K');
INSERT INTO "public"."suppliers" VALUES (121, NULL, NULL, '0120', 'SURESH');
INSERT INTO "public"."suppliers" VALUES (122, NULL, NULL, '0121', 'JUL');
INSERT INTO "public"."suppliers" VALUES (123, NULL, NULL, '0122', 'ACIEN/HERRIS TRADING (AT)');
INSERT INTO "public"."suppliers" VALUES (124, NULL, NULL, '0123', 'IING BPR');
INSERT INTO "public"."suppliers" VALUES (125, NULL, NULL, '0124', 'DEVA');
INSERT INTO "public"."suppliers" VALUES (126, NULL, NULL, '0125', 'ANDY RAUM/VERONICA');
INSERT INTO "public"."suppliers" VALUES (127, NULL, NULL, '0126', 'LARISH F');
INSERT INTO "public"."suppliers" VALUES (128, NULL, NULL, '0127', 'ABDILLAH/FADILLAH');
INSERT INTO "public"."suppliers" VALUES (129, NULL, NULL, '0128', 'AXEL');
INSERT INTO "public"."suppliers" VALUES (130, NULL, NULL, '0129', 'BOLA MAS');
INSERT INTO "public"."suppliers" VALUES (131, NULL, NULL, '0130', 'ADIS');
INSERT INTO "public"."suppliers" VALUES (132, NULL, NULL, '0131', 'RENA/ARGA');
INSERT INTO "public"."suppliers" VALUES (133, NULL, NULL, '0132', 'MITRA COLLECTION');
INSERT INTO "public"."suppliers" VALUES (134, NULL, NULL, '0133', 'MAKRO');
INSERT INTO "public"."suppliers" VALUES (135, NULL, NULL, '0134', 'MODIFIKASI');
INSERT INTO "public"."suppliers" VALUES (136, NULL, NULL, '0135', 'UCENG/RINA LATIFAH');
INSERT INTO "public"."suppliers" VALUES (137, NULL, NULL, '0136', 'LITTLE INK');
INSERT INTO "public"."suppliers" VALUES (138, NULL, NULL, '0137', 'BAYU (BY)');
INSERT INTO "public"."suppliers" VALUES (139, NULL, NULL, '0138', 'HENNY LIMANTO');
INSERT INTO "public"."suppliers" VALUES (140, NULL, NULL, '0139', 'TEGUH/SINAR SELATAN');
INSERT INTO "public"."suppliers" VALUES (141, NULL, NULL, '0140', 'LISNA/HERMAN');
INSERT INTO "public"."suppliers" VALUES (142, NULL, NULL, '0141', 'MINDA');
INSERT INTO "public"."suppliers" VALUES (143, NULL, NULL, '0142', 'LIA TAMAN MUTIARA');
INSERT INTO "public"."suppliers" VALUES (144, NULL, NULL, '0143', 'GRANDE');
INSERT INTO "public"."suppliers" VALUES (145, NULL, NULL, '0144', 'LUMBUNG PADI');
INSERT INTO "public"."suppliers" VALUES (146, NULL, NULL, '0145', 'KARAN');
INSERT INTO "public"."suppliers" VALUES (147, NULL, NULL, '0146', 'DEVA I PUTRA / SEMANGAT ERA MANDIRI');
INSERT INTO "public"."suppliers" VALUES (148, NULL, NULL, '0147', 'MEGAWATI');
INSERT INTO "public"."suppliers" VALUES (149, NULL, NULL, '0148', 'ENDI (EI)');
INSERT INTO "public"."suppliers" VALUES (150, NULL, NULL, '0149', 'YOGO BEKASI');
INSERT INTO "public"."suppliers" VALUES (151, NULL, NULL, '0150', 'IPE PURWANTO');
INSERT INTO "public"."suppliers" VALUES (152, NULL, NULL, '0151', 'ROY (KALENDER)');
INSERT INTO "public"."suppliers" VALUES (153, NULL, NULL, '0152', 'ASEP BERLIAN');
INSERT INTO "public"."suppliers" VALUES (154, NULL, NULL, '0153', 'MULTI BROTHER');
INSERT INTO "public"."suppliers" VALUES (155, NULL, NULL, '0154', 'GUNAWAN T');
INSERT INTO "public"."suppliers" VALUES (156, NULL, NULL, '0155', 'UNIQUE');
INSERT INTO "public"."suppliers" VALUES (157, NULL, NULL, '0156', 'ERWI LEGOK');
INSERT INTO "public"."suppliers" VALUES (158, NULL, NULL, '0157', 'ADE FH/FA-FA');
INSERT INTO "public"."suppliers" VALUES (159, NULL, NULL, '0158', 'PT GMT');
INSERT INTO "public"."suppliers" VALUES (160, NULL, NULL, '0159', 'H MADI 730');
INSERT INTO "public"."suppliers" VALUES (161, NULL, NULL, '0160', '"ANDY LUKMAN 700');
INSERT INTO "public"."suppliers" VALUES (162, NULL, NULL, '0161', 'BUDI WILKY');
INSERT INTO "public"."suppliers" VALUES (163, NULL, NULL, '0162', 'AMIE');
INSERT INTO "public"."suppliers" VALUES (164, NULL, NULL, '0163', 'WIYANTO');
INSERT INTO "public"."suppliers" VALUES (165, NULL, NULL, '0164', 'MARK');
INSERT INTO "public"."suppliers" VALUES (166, NULL, NULL, '0165', 'EDWAN SHARON');
INSERT INTO "public"."suppliers" VALUES (167, NULL, NULL, '0166', 'PT SOCKA FARGE INDONESIA');
INSERT INTO "public"."suppliers" VALUES (168, NULL, NULL, '0167', 'AAS');
INSERT INTO "public"."suppliers" VALUES (169, NULL, NULL, '0168', 'SUPLIER MIX');
INSERT INTO "public"."suppliers" VALUES (170, NULL, NULL, '0169', 'JENNY SEMARANG');
INSERT INTO "public"."suppliers" VALUES (171, NULL, NULL, '0170', 'TEJA');
INSERT INTO "public"."suppliers" VALUES (172, NULL, NULL, '0171', 'PAULINE');
INSERT INTO "public"."suppliers" VALUES (173, NULL, NULL, '0172', 'MUMPHIS(MM)');
INSERT INTO "public"."suppliers" VALUES (174, NULL, NULL, '0173', 'SUHAIMI');
INSERT INTO "public"."suppliers" VALUES (175, NULL, NULL, '0174', 'ANO');
INSERT INTO "public"."suppliers" VALUES (176, NULL, NULL, '0175', 'FAHMI');
INSERT INTO "public"."suppliers" VALUES (177, NULL, NULL, '0176', 'SUWOTO/ATIYAH');
INSERT INTO "public"."suppliers" VALUES (178, NULL, NULL, '0177', 'INNA APPAREL/CHRISTIANTO');
INSERT INTO "public"."suppliers" VALUES (179, NULL, NULL, '0178', 'DARMA MERUA');
INSERT INTO "public"."suppliers" VALUES (180, NULL, NULL, '0179', 'ENGKOS (ES)');
INSERT INTO "public"."suppliers" VALUES (181, NULL, NULL, '0180', 'KAMPUNG DAUN');
INSERT INTO "public"."suppliers" VALUES (182, NULL, NULL, '0181', 'KOMALA');
INSERT INTO "public"."suppliers" VALUES (183, NULL, NULL, '0182', 'STEVE');
INSERT INTO "public"."suppliers" VALUES (184, NULL, NULL, '0183', 'EXPORT STATION');
INSERT INTO "public"."suppliers" VALUES (185, NULL, NULL, '0184', 'PT WISKA');
INSERT INTO "public"."suppliers" VALUES (186, NULL, NULL, '0185', 'BENNI SUHERLAN');
INSERT INTO "public"."suppliers" VALUES (187, NULL, NULL, '0186', 'ICAL');
INSERT INTO "public"."suppliers" VALUES (188, NULL, NULL, '0187', 'MEGAWATI W/ACCHEDYA COLLECTION');
INSERT INTO "public"."suppliers" VALUES (189, NULL, NULL, '0188', 'MANOJ D MUN WANI');
INSERT INTO "public"."suppliers" VALUES (190, NULL, NULL, '0189', 'NAEEM');
INSERT INTO "public"."suppliers" VALUES (191, NULL, NULL, '0190', 'KAMAL');
INSERT INTO "public"."suppliers" VALUES (192, NULL, NULL, '0191', 'MARINA');
INSERT INTO "public"."suppliers" VALUES (193, NULL, NULL, '0192', 'ANDI KIM (AK)');
INSERT INTO "public"."suppliers" VALUES (194, NULL, NULL, '0193', 'TOTO SUTANTO');
INSERT INTO "public"."suppliers" VALUES (195, NULL, NULL, '0194', 'AAN');
INSERT INTO "public"."suppliers" VALUES (196, NULL, NULL, '0195', 'H. MAS UD (234/203)');
INSERT INTO "public"."suppliers" VALUES (197, NULL, NULL, '0196', 'AKUY');
INSERT INTO "public"."suppliers" VALUES (198, NULL, NULL, '0197', 'ANDREW');
INSERT INTO "public"."suppliers" VALUES (199, NULL, NULL, '0198', 'ANDRI LAPUMA');
INSERT INTO "public"."suppliers" VALUES (200, NULL, NULL, '0199', 'PT KAPASINDO PRIMA');
INSERT INTO "public"."suppliers" VALUES (201, NULL, NULL, '0200', 'LILY BHC/LILY DEVIANI HIDAYAT');
INSERT INTO "public"."suppliers" VALUES (202, NULL, NULL, '0201', 'WIMA BUSANA');
INSERT INTO "public"."suppliers" VALUES (203, NULL, NULL, '0202', 'SIAW HUNG');
INSERT INTO "public"."suppliers" VALUES (204, NULL, NULL, '0203', 'ADENG');
INSERT INTO "public"."suppliers" VALUES (205, NULL, NULL, '0204', 'PAKAR SEMBILAN/IRFAN');
INSERT INTO "public"."suppliers" VALUES (206, NULL, NULL, '0205', 'ROSINI');
INSERT INTO "public"."suppliers" VALUES (207, NULL, NULL, '0206', 'LISKE');
INSERT INTO "public"."suppliers" VALUES (208, NULL, NULL, '0207', 'HANDOYO');
INSERT INTO "public"."suppliers" VALUES (209, NULL, NULL, '0208', 'MAIDASRIL');
INSERT INTO "public"."suppliers" VALUES (210, NULL, NULL, '0209', 'IMEL');
INSERT INTO "public"."suppliers" VALUES (211, NULL, NULL, '0210', 'DILLA');
INSERT INTO "public"."suppliers" VALUES (212, NULL, NULL, '0211', 'PT DAESE GARMENT');
INSERT INTO "public"."suppliers" VALUES (213, NULL, NULL, '0212', 'JORDAN');
INSERT INTO "public"."suppliers" VALUES (214, NULL, NULL, '0213', 'ROBERT RAFFAEL');
INSERT INTO "public"."suppliers" VALUES (215, NULL, NULL, '0214', 'HORNEST');
INSERT INTO "public"."suppliers" VALUES (216, NULL, NULL, '0215', 'SANTOSA JAYA');
INSERT INTO "public"."suppliers" VALUES (217, NULL, NULL, '0216', 'PT SINARRIMPEx');
INSERT INTO "public"."suppliers" VALUES (218, NULL, NULL, '0217', 'BENNY ANDERSON');
INSERT INTO "public"."suppliers" VALUES (219, NULL, NULL, '0218', 'PT. GISTEX');
INSERT INTO "public"."suppliers" VALUES (220, NULL, NULL, '0219', 'UNGARAN');
INSERT INTO "public"."suppliers" VALUES (221, NULL, NULL, '0220', 'SHERLY');
INSERT INTO "public"."suppliers" VALUES (222, NULL, NULL, '0221', 'TOKO M2');
INSERT INTO "public"."suppliers" VALUES (223, NULL, NULL, '0222', 'IING/SUSAN BLOOMING (547)');
INSERT INTO "public"."suppliers" VALUES (224, NULL, NULL, '0223', 'PT YOSAFAT ADIDAYA/LUCAS');
INSERT INTO "public"."suppliers" VALUES (225, NULL, NULL, '0224', 'S. SIMAMORA');
INSERT INTO "public"."suppliers" VALUES (226, NULL, NULL, '0225', 'H MAS UD (234/203)');
INSERT INTO "public"."suppliers" VALUES (227, NULL, NULL, '0226', 'PT MASCOTINDO');
INSERT INTO "public"."suppliers" VALUES (228, NULL, NULL, '0227', 'JESSICA/SELVIE');
INSERT INTO "public"."suppliers" VALUES (229, NULL, NULL, '0228', 'PT MGP ( MITRA GARINDO PERKASA )');
INSERT INTO "public"."suppliers" VALUES (230, NULL, NULL, '0229', '"BENNY T 239');
INSERT INTO "public"."suppliers" VALUES (231, NULL, NULL, '0230', 'H AWING');
INSERT INTO "public"."suppliers" VALUES (232, NULL, NULL, '0231', 'GCR/GRACE BR');
INSERT INTO "public"."suppliers" VALUES (233, NULL, NULL, '0232', 'LUCAS');
INSERT INTO "public"."suppliers" VALUES (234, NULL, NULL, '0233', 'ANTON L.BCA ( 745/237/243/172)');
INSERT INTO "public"."suppliers" VALUES (235, NULL, NULL, '0234', 'EDI PURNAMA');
INSERT INTO "public"."suppliers" VALUES (236, NULL, NULL, '0235', 'KAROLINA/CAMAR');
INSERT INTO "public"."suppliers" VALUES (237, NULL, NULL, '0236', 'UNGARAN');
INSERT INTO "public"."suppliers" VALUES (238, NULL, NULL, '0237', 'IBU I YEN');
INSERT INTO "public"."suppliers" VALUES (239, NULL, NULL, '0238', 'SUHANDI/BANDUNG STOCK LOT CENTRE');
INSERT INTO "public"."suppliers" VALUES (240, NULL, NULL, '0239', 'YUSUF 475');
INSERT INTO "public"."suppliers" VALUES (241, NULL, NULL, '0240', 'LILY UTARIA/JKT');
INSERT INTO "public"."suppliers" VALUES (242, NULL, NULL, '0241', 'RIENA SUSANTI');
INSERT INTO "public"."suppliers" VALUES (243, NULL, NULL, '0242', 'IING BARU/CAKRAWALA 647');
INSERT INTO "public"."suppliers" VALUES (244, NULL, NULL, '0243', 'PT CAS');
INSERT INTO "public"."suppliers" VALUES (245, NULL, NULL, '0244', 'ANITA FASHION');
INSERT INTO "public"."suppliers" VALUES (246, NULL, NULL, '0245', 'ERLIN');
INSERT INTO "public"."suppliers" VALUES (247, NULL, NULL, '0246', 'BINA CITRA');
INSERT INTO "public"."suppliers" VALUES (248, NULL, NULL, '0247', 'ROMLI');
INSERT INTO "public"."suppliers" VALUES (249, NULL, NULL, '0248', 'PT INDUSTRI INDAH JAYA');
INSERT INTO "public"."suppliers" VALUES (250, NULL, NULL, '0249', 'LILI/TAN MEI LIE');
INSERT INTO "public"."suppliers" VALUES (251, NULL, NULL, '0250', 'YULIAWATI CHRISTIAN');
INSERT INTO "public"."suppliers" VALUES (252, NULL, NULL, '0251', 'MAYOR JUN (261/338)');
INSERT INTO "public"."suppliers" VALUES (253, NULL, NULL, '0252', 'YANTI/VALERIE COLL');
INSERT INTO "public"."suppliers" VALUES (254, NULL, NULL, '0253', 'EKA/BENYAMIN');
INSERT INTO "public"."suppliers" VALUES (255, NULL, NULL, '0254', 'PT PICAERINDO ABADI JAYA');
INSERT INTO "public"."suppliers" VALUES (256, NULL, NULL, '0255', 'HENDRI/VINCE');
INSERT INTO "public"."suppliers" VALUES (257, NULL, NULL, '0256', 'JAYA MULYA');
INSERT INTO "public"."suppliers" VALUES (258, NULL, NULL, '0257', 'TWIG HOUSE/KIOK');
INSERT INTO "public"."suppliers" VALUES (259, NULL, NULL, '0258', 'EUGENIA');
INSERT INTO "public"."suppliers" VALUES (260, NULL, NULL, '0259', 'PT PONI');
INSERT INTO "public"."suppliers" VALUES (261, NULL, NULL, '0260', 'IWAN');
INSERT INTO "public"."suppliers" VALUES (262, NULL, NULL, '0261', 'KAYDEE');
INSERT INTO "public"."suppliers" VALUES (263, NULL, NULL, '0262', 'GAUDI');
INSERT INTO "public"."suppliers" VALUES (264, NULL, NULL, '0263', 'SUN TJIANG');
INSERT INTO "public"."suppliers" VALUES (265, NULL, NULL, '0264', 'ACIM');
INSERT INTO "public"."suppliers" VALUES (266, NULL, NULL, '0265', 'PT CAS (253/418/503/638/275)');
INSERT INTO "public"."suppliers" VALUES (267, NULL, NULL, '0266', 'LISA');
INSERT INTO "public"."suppliers" VALUES (268, NULL, NULL, '0267', 'GENTA');
INSERT INTO "public"."suppliers" VALUES (269, NULL, NULL, '0268', 'MR GOFU (713/622/278)');
INSERT INTO "public"."suppliers" VALUES (270, NULL, NULL, '0269', 'AMIRA (AM)');
INSERT INTO "public"."suppliers" VALUES (271, NULL, NULL, '0270', 'NELLY NURDIANI/WINS FASHION');
INSERT INTO "public"."suppliers" VALUES (272, NULL, NULL, '0271', 'CAROLINE');
INSERT INTO "public"."suppliers" VALUES (273, NULL, NULL, '0272', 'UCHIE/SISKA');
INSERT INTO "public"."suppliers" VALUES (274, NULL, NULL, '0273', 'ROBIN II');
INSERT INTO "public"."suppliers" VALUES (275, NULL, NULL, '0274', 'SANDRA');
INSERT INTO "public"."suppliers" VALUES (276, NULL, NULL, '0275', 'REI SUNG');
INSERT INTO "public"."suppliers" VALUES (277, NULL, NULL, '0276', 'WANDI');
INSERT INTO "public"."suppliers" VALUES (278, NULL, NULL, '0277', 'ANNA DESIGN');
INSERT INTO "public"."suppliers" VALUES (279, NULL, NULL, '0278', 'QUICK (Q)');
INSERT INTO "public"."suppliers" VALUES (280, NULL, NULL, '0279', 'NOVA FASHION');
INSERT INTO "public"."suppliers" VALUES (281, NULL, NULL, '0280', 'PT DUTA MANDIRI PERKAS (DMP)/HERMAN');
INSERT INTO "public"."suppliers" VALUES (282, NULL, NULL, '0281', 'T.PENGKOLAN');
INSERT INTO "public"."suppliers" VALUES (283, NULL, NULL, '0282', 'ELIA/BIG FASHION');
INSERT INTO "public"."suppliers" VALUES (284, NULL, NULL, '0283', 'BUDI/ALEX');
INSERT INTO "public"."suppliers" VALUES (285, NULL, NULL, '0284', 'INDRI');
INSERT INTO "public"."suppliers" VALUES (286, NULL, NULL, '0285', 'PT JAVA INDO PRINT');
INSERT INTO "public"."suppliers" VALUES (287, NULL, NULL, '0286', 'BARNUS/VILLICIANUS');
INSERT INTO "public"."suppliers" VALUES (288, NULL, NULL, '0287', 'PIPIN');
INSERT INTO "public"."suppliers" VALUES (289, NULL, NULL, '0288', 'PT PESONA GARMENT/DANNY');
INSERT INTO "public"."suppliers" VALUES (290, NULL, NULL, '0289', 'AAS UNGARAN');
INSERT INTO "public"."suppliers" VALUES (291, NULL, NULL, '0290', 'DALANTA BUKIT');
INSERT INTO "public"."suppliers" VALUES (292, NULL, NULL, '0291', 'ANDI LUKMAN');
INSERT INTO "public"."suppliers" VALUES (293, NULL, NULL, '0292', 'CANIA');
INSERT INTO "public"."suppliers" VALUES (294, NULL, NULL, '0293', 'THAI THAI SHOP');
INSERT INTO "public"."suppliers" VALUES (295, NULL, NULL, '0294', 'BIG PULL');
INSERT INTO "public"."suppliers" VALUES (296, NULL, NULL, '0295', 'HARISH KUMAR');
INSERT INTO "public"."suppliers" VALUES (297, NULL, NULL, '0296', 'PD FAJAR PRIMA /BUDI BENNY (FP)');
INSERT INTO "public"."suppliers" VALUES (298, NULL, NULL, '0297', 'CV BINTANG ARGO/AGUS SISWANDY');
INSERT INTO "public"."suppliers" VALUES (299, NULL, NULL, '0298', 'NOVI/BEAR');
INSERT INTO "public"."suppliers" VALUES (300, NULL, NULL, '0299', 'PT MEGA/PRAKASH');
INSERT INTO "public"."suppliers" VALUES (301, NULL, NULL, '0300', 'TOKO 32 ANDIR');
INSERT INTO "public"."suppliers" VALUES (302, NULL, NULL, '0301', 'SHERLY INDRI');
INSERT INTO "public"."suppliers" VALUES (303, NULL, NULL, '0302', 'TEGUH');
INSERT INTO "public"."suppliers" VALUES (304, NULL, NULL, '0303', 'JAYA LESTARI');
INSERT INTO "public"."suppliers" VALUES (305, NULL, NULL, '0304', 'YAN SETIO');
INSERT INTO "public"."suppliers" VALUES (306, NULL, NULL, '0305', 'STEPHANUS');
INSERT INTO "public"."suppliers" VALUES (307, NULL, NULL, '0306', 'BUMIWANA USAHA JAYA ( BUJ )');
INSERT INTO "public"."suppliers" VALUES (308, NULL, NULL, '0307', 'SURONO (SO)');
INSERT INTO "public"."suppliers" VALUES (309, NULL, NULL, '0308', 'JOHAN SUSANTO/INTITEX');
INSERT INTO "public"."suppliers" VALUES (310, NULL, NULL, '0309', 'PT ISANTI JAYA');
INSERT INTO "public"."suppliers" VALUES (311, NULL, NULL, '0310', 'ICT/ENGGARYANI IRAWAN');
INSERT INTO "public"."suppliers" VALUES (312, NULL, NULL, '0311', 'NATATEX/KURNIADI');
INSERT INTO "public"."suppliers" VALUES (313, NULL, NULL, '0312', 'MING YEN');
INSERT INTO "public"."suppliers" VALUES (314, NULL, NULL, '0313', 'BUSANA INDAH');
INSERT INTO "public"."suppliers" VALUES (315, NULL, NULL, '0314', 'PT BPG');
INSERT INTO "public"."suppliers" VALUES (316, NULL, NULL, '0315', 'BERKAT JAYA');
INSERT INTO "public"."suppliers" VALUES (317, NULL, NULL, '0316', 'METRO GARMENT');
INSERT INTO "public"."suppliers" VALUES (318, NULL, NULL, '0317', 'MULIA JAYA/EKRILO');
INSERT INTO "public"."suppliers" VALUES (319, NULL, NULL, '0318', 'LUCA BOSSI');
INSERT INTO "public"."suppliers" VALUES (320, NULL, NULL, '0319', 'ROSITA');
INSERT INTO "public"."suppliers" VALUES (321, NULL, NULL, '0320', 'PT.AMEYA LIVINGSTYLE (AL)');
INSERT INTO "public"."suppliers" VALUES (322, NULL, NULL, '0321', 'ULUNG');
INSERT INTO "public"."suppliers" VALUES (323, NULL, NULL, '0322', 'AGNES');
INSERT INTO "public"."suppliers" VALUES (324, NULL, NULL, '0323', 'BENNY KBJ');
INSERT INTO "public"."suppliers" VALUES (325, NULL, NULL, '0324', 'MAYOR JUN 261');
INSERT INTO "public"."suppliers" VALUES (326, NULL, NULL, '0325', 'WILLIAM INE (WI)');
INSERT INTO "public"."suppliers" VALUES (327, NULL, NULL, '0326', 'CARGO FACTORY OUTLET');
INSERT INTO "public"."suppliers" VALUES (328, NULL, NULL, '0327', 'BLOSSOM FO');
INSERT INTO "public"."suppliers" VALUES (329, NULL, NULL, '0328', 'WINDRA DENIM (WD)');
INSERT INTO "public"."suppliers" VALUES (330, NULL, NULL, '0329', 'BLACK MARKET');
INSERT INTO "public"."suppliers" VALUES (331, NULL, NULL, '0330', 'UJANG SULAEMAN');
INSERT INTO "public"."suppliers" VALUES (332, NULL, NULL, '0331', 'PT GIVEMAS');
INSERT INTO "public"."suppliers" VALUES (333, NULL, NULL, '0332', 'YUSITO');
INSERT INTO "public"."suppliers" VALUES (334, NULL, NULL, '0333', 'SUTRISNO/SINSIN');
INSERT INTO "public"."suppliers" VALUES (335, NULL, NULL, '0334', 'MOI FO JKT');
INSERT INTO "public"."suppliers" VALUES (336, NULL, NULL, '0335', 'KIM IN SOO');
INSERT INTO "public"."suppliers" VALUES (337, NULL, NULL, '0336', 'MEGA/ JASEON');
INSERT INTO "public"."suppliers" VALUES (338, NULL, NULL, '0337', 'ANUGERAH PRATMA BUSANA');
INSERT INTO "public"."suppliers" VALUES (339, NULL, NULL, '0338', 'TERMINAL MODE');
INSERT INTO "public"."suppliers" VALUES (340, NULL, NULL, '0339', 'PT.TYFOUNTEX INDONESIA');
INSERT INTO "public"."suppliers" VALUES (341, NULL, NULL, '0340', 'AGUS / HERI');
INSERT INTO "public"."suppliers" VALUES (342, NULL, NULL, '0341', 'HERMAN');
INSERT INTO "public"."suppliers" VALUES (343, NULL, NULL, '0342', 'STYLE/NICE');
INSERT INTO "public"."suppliers" VALUES (344, NULL, NULL, '0343', 'BUAH BATU STOCK LN');
INSERT INTO "public"."suppliers" VALUES (345, NULL, NULL, '0344', 'LEONARDI');
INSERT INTO "public"."suppliers" VALUES (346, NULL, NULL, '0345', 'PT SINAR APPAREL INDONESIA');
INSERT INTO "public"."suppliers" VALUES (347, NULL, NULL, '0346', 'BEST CHOICE');
INSERT INTO "public"."suppliers" VALUES (348, NULL, NULL, '0347', 'ANDRI SOKA');
INSERT INTO "public"."suppliers" VALUES (349, NULL, NULL, '0348', 'VICKY TOYS/DAVID');
INSERT INTO "public"."suppliers" VALUES (350, NULL, NULL, '0349', 'PT BHARAT TRADING');
INSERT INTO "public"."suppliers" VALUES (351, NULL, NULL, '0350', 'JANTY (JY)');
INSERT INTO "public"."suppliers" VALUES (352, NULL, NULL, '0351', 'EMMY');
INSERT INTO "public"."suppliers" VALUES (353, NULL, NULL, '0352', 'EL-HA FASHION');
INSERT INTO "public"."suppliers" VALUES (354, NULL, NULL, '0353', 'ALBERT TJAHYADI');
INSERT INTO "public"."suppliers" VALUES (355, NULL, NULL, '0354', 'FARID');
INSERT INTO "public"."suppliers" VALUES (356, NULL, NULL, '0355', 'CHRISTINA');
INSERT INTO "public"."suppliers" VALUES (357, NULL, NULL, '0356', 'HANNY G');
INSERT INTO "public"."suppliers" VALUES (358, NULL, NULL, '0357', 'HANNIE DESIGN');
INSERT INTO "public"."suppliers" VALUES (359, NULL, NULL, '0358', 'PT STARINDO JAYA UTAMA/ IBU II');
INSERT INTO "public"."suppliers" VALUES (360, NULL, NULL, '0359', 'SM GARMENT');
INSERT INTO "public"."suppliers" VALUES (361, NULL, NULL, '0360', 'RAJU/DAVE');
INSERT INTO "public"."suppliers" VALUES (362, NULL, NULL, '0361', 'I KHWANUDIN /UD SEDERHANA');
INSERT INTO "public"."suppliers" VALUES (363, NULL, NULL, '0362', 'PT ARTA RAYA');
INSERT INTO "public"."suppliers" VALUES (364, NULL, NULL, '0363', 'LOTUS');
INSERT INTO "public"."suppliers" VALUES (365, NULL, NULL, '0364', 'SIPAHUTAR');
INSERT INTO "public"."suppliers" VALUES (366, NULL, NULL, '0365', 'LILIYANTI ONGGOWASITO');
INSERT INTO "public"."suppliers" VALUES (367, NULL, NULL, '0366', 'SINAR MAS');
INSERT INTO "public"."suppliers" VALUES (368, NULL, NULL, '0367', 'GRAHA BUSANA LESTARI');
INSERT INTO "public"."suppliers" VALUES (369, NULL, NULL, '0368', 'YITNO');
INSERT INTO "public"."suppliers" VALUES (370, NULL, NULL, '0369', 'SHELLY MALIKI');
INSERT INTO "public"."suppliers" VALUES (371, NULL, NULL, '0370', 'TUWUH PRATIWI');
INSERT INTO "public"."suppliers" VALUES (372, NULL, NULL, '0371', 'DARMADJI/UD SEDERHANA');
INSERT INTO "public"."suppliers" VALUES (373, NULL, NULL, '0372', 'WIJAYA');
INSERT INTO "public"."suppliers" VALUES (374, NULL, NULL, '0373', 'LIA/LICOS');
INSERT INTO "public"."suppliers" VALUES (375, NULL, NULL, '0374', 'B BOS');
INSERT INTO "public"."suppliers" VALUES (376, NULL, NULL, '0375', 'AAN UNGARAN');
INSERT INTO "public"."suppliers" VALUES (377, NULL, NULL, '0376', 'DJAP/ANTONI (DA)');
INSERT INTO "public"."suppliers" VALUES (378, NULL, NULL, '0377', 'AKIET');
INSERT INTO "public"."suppliers" VALUES (379, NULL, NULL, '0378', 'DAVE');
INSERT INTO "public"."suppliers" VALUES (380, NULL, NULL, '0379', 'HERU/RYAN COLLECTION');
INSERT INTO "public"."suppliers" VALUES (381, NULL, NULL, '0380', 'YANCE');
INSERT INTO "public"."suppliers" VALUES (382, NULL, NULL, '0381', 'CAREFOURE');
INSERT INTO "public"."suppliers" VALUES (383, NULL, NULL, '0382', 'MARIA (MA)');
INSERT INTO "public"."suppliers" VALUES (384, NULL, NULL, '0383', 'ERNI');
INSERT INTO "public"."suppliers" VALUES (385, NULL, NULL, '0384', 'FREDDY TANU');
INSERT INTO "public"."suppliers" VALUES (386, NULL, NULL, '0385', 'RAMA TUNGGAL/RAMADHAN');
INSERT INTO "public"."suppliers" VALUES (387, NULL, NULL, '0386', 'CV TIRTA KENCANA  MANDIRI/DADANG');
INSERT INTO "public"."suppliers" VALUES (388, NULL, NULL, '0387', 'PT UNGARAN SARI(246');
INSERT INTO "public"."suppliers" VALUES (389, NULL, NULL, '0388', 'HANSON INDUSTRI UTAMA TBK');
INSERT INTO "public"."suppliers" VALUES (390, NULL, NULL, '0389', 'WINS FASHION/NELLY');
INSERT INTO "public"."suppliers" VALUES (391, NULL, NULL, '0390', 'YOGYA');
INSERT INTO "public"."suppliers" VALUES (392, NULL, NULL, '0391', 'WORLD SHOP 9999');
INSERT INTO "public"."suppliers" VALUES (393, NULL, NULL, '0392', 'PT ESWON  MAS SENTOSA/MR HONG');
INSERT INTO "public"."suppliers" VALUES (394, NULL, NULL, '0393', 'BRASCO');
INSERT INTO "public"."suppliers" VALUES (395, NULL, NULL, '0394', 'UD RIZKY SUKSES MANDIRI');
INSERT INTO "public"."suppliers" VALUES (396, NULL, NULL, '0395', 'MR KEVIN');
INSERT INTO "public"."suppliers" VALUES (397, NULL, NULL, '0396', 'TUNG MEI /MDC');
INSERT INTO "public"."suppliers" VALUES (398, NULL, NULL, '0397', 'CARVIENO /CV JKL');
INSERT INTO "public"."suppliers" VALUES (399, NULL, NULL, '0398', 'MAJESTY COLL');
INSERT INTO "public"."suppliers" VALUES (400, NULL, NULL, '0399', '"M&M DAGO');
INSERT INTO "public"."suppliers" VALUES (401, NULL, NULL, '0400', 'LIDIA');
INSERT INTO "public"."suppliers" VALUES (402, NULL, NULL, '0401', 'DIAH');
INSERT INTO "public"."suppliers" VALUES (403, NULL, NULL, '0402', 'MR LEE  WAN YOUNG');
INSERT INTO "public"."suppliers" VALUES (404, NULL, NULL, '0403', 'PT CAS 253');
INSERT INTO "public"."suppliers" VALUES (405, NULL, NULL, '0404', 'PT SANGWOO /MR OH');
INSERT INTO "public"."suppliers" VALUES (406, NULL, NULL, '0405', 'LIONG SUSAN');
INSERT INTO "public"."suppliers" VALUES (407, NULL, NULL, '0406', 'KING COLLECTION');
INSERT INTO "public"."suppliers" VALUES (408, NULL, NULL, '0407', 'EMY');
INSERT INTO "public"."suppliers" VALUES (409, NULL, NULL, '0408', 'DOENG (DG)');
INSERT INTO "public"."suppliers" VALUES (410, NULL, NULL, '0409', 'AAM');
INSERT INTO "public"."suppliers" VALUES (411, NULL, NULL, '0410', 'THE BEAR');
INSERT INTO "public"."suppliers" VALUES (412, NULL, NULL, '0411', 'DJAYA FASHION/EKA DJAYA');
INSERT INTO "public"."suppliers" VALUES (413, NULL, NULL, '0412', 'AYUNG');
INSERT INTO "public"."suppliers" VALUES (414, NULL, NULL, '0413', 'RUDI CEMPAKA');
INSERT INTO "public"."suppliers" VALUES (415, NULL, NULL, '0414', 'DINDRO SUSANTO (DS)');
INSERT INTO "public"."suppliers" VALUES (416, NULL, NULL, '0415', 'ERI SALATIGA ( ES )');
INSERT INTO "public"."suppliers" VALUES (417, NULL, NULL, '0416', 'ROHMAN');
INSERT INTO "public"."suppliers" VALUES (418, NULL, NULL, '0417', 'SUBHI');
INSERT INTO "public"."suppliers" VALUES (419, NULL, NULL, '0418', 'CITRA BUSANA INDONESIA/MITRA SUKSES');
INSERT INTO "public"."suppliers" VALUES (420, NULL, NULL, '0419', 'MARTIN B');
INSERT INTO "public"."suppliers" VALUES (421, NULL, NULL, '0420', 'STEVEN/RINI (MAJU INDAH GARMENDO)');
INSERT INTO "public"."suppliers" VALUES (422, NULL, NULL, '0421', 'MEKAR JAYA MANDIRI');
INSERT INTO "public"."suppliers" VALUES (423, NULL, NULL, '0422', 'BUDI ALDI');
INSERT INTO "public"."suppliers" VALUES (424, NULL, NULL, '0423', 'INDO GROSIR');
INSERT INTO "public"."suppliers" VALUES (425, NULL, NULL, '0424', 'HERWAN/TOTO');
INSERT INTO "public"."suppliers" VALUES (426, NULL, NULL, '0425', 'BUCHARI');
INSERT INTO "public"."suppliers" VALUES (427, NULL, NULL, '0426', 'YOCOCO BUSANA');
INSERT INTO "public"."suppliers" VALUES (428, NULL, NULL, '0427', 'PRIMA');
INSERT INTO "public"."suppliers" VALUES (429, NULL, NULL, '0428', 'THE BEAR');
INSERT INTO "public"."suppliers" VALUES (430, NULL, NULL, '0429', 'CIBADAK/PD TERUS MAKMUR/T.HEGAR');
INSERT INTO "public"."suppliers" VALUES (431, NULL, NULL, '0430', 'AMELIA');
INSERT INTO "public"."suppliers" VALUES (432, NULL, NULL, '0431', 'YUKI/ROSDIANA');
INSERT INTO "public"."suppliers" VALUES (433, NULL, NULL, '0432', 'METI');
INSERT INTO "public"."suppliers" VALUES (434, NULL, NULL, '0433', 'TDM/FIVI (SANGKIONG)');
INSERT INTO "public"."suppliers" VALUES (435, NULL, NULL, '0434', 'PT BPG');
INSERT INTO "public"."suppliers" VALUES (436, NULL, NULL, '0435', 'IBU SETIAWAN');
INSERT INTO "public"."suppliers" VALUES (437, NULL, NULL, '0436', 'KETUT KRISBIANTORO (KK)');
INSERT INTO "public"."suppliers" VALUES (438, NULL, NULL, '0437', 'SUMMIT');
INSERT INTO "public"."suppliers" VALUES (439, NULL, NULL, '0438', 'MARCHE');
INSERT INTO "public"."suppliers" VALUES (440, NULL, NULL, '0439', 'CORAL FO');
INSERT INTO "public"."suppliers" VALUES (441, NULL, NULL, '0440', 'PT JAYA CAHYA AGUNG/VICTORIA');
INSERT INTO "public"."suppliers" VALUES (442, NULL, NULL, '0441', 'ATIYAH');
INSERT INTO "public"."suppliers" VALUES (443, NULL, NULL, '0442', 'ANES');
INSERT INTO "public"."suppliers" VALUES (444, NULL, NULL, '0443', 'SUSIE/SISILIA');
INSERT INTO "public"."suppliers" VALUES (445, NULL, NULL, '0444', 'HERITAGE');
INSERT INTO "public"."suppliers" VALUES (446, NULL, NULL, '0445', 'VERONICA');
INSERT INTO "public"."suppliers" VALUES (447, NULL, NULL, '0446', 'SASHA & POPY COLL');
INSERT INTO "public"."suppliers" VALUES (448, NULL, NULL, '0447', 'TRI TUNGGAL');
INSERT INTO "public"."suppliers" VALUES (449, NULL, NULL, '0448', 'PARKIR FO');
INSERT INTO "public"."suppliers" VALUES (450, NULL, NULL, '0449', 'TIMUR JAYA ABADI');
INSERT INTO "public"."suppliers" VALUES (451, NULL, NULL, '0450', 'INDO ANIL MANDIRI');
INSERT INTO "public"."suppliers" VALUES (452, NULL, NULL, '0451', 'YACOCO BUSANA');
INSERT INTO "public"."suppliers" VALUES (453, NULL, NULL, '0452', 'TOKO HEGAR');
INSERT INTO "public"."suppliers" VALUES (454, NULL, NULL, '0453', 'TEDY');
INSERT INTO "public"."suppliers" VALUES (455, NULL, NULL, '0454', 'KIKI SUSILO');
INSERT INTO "public"."suppliers" VALUES (456, NULL, NULL, '0455', 'CIPTADI PRIMA MANDIRI');
INSERT INTO "public"."suppliers" VALUES (457, NULL, NULL, '0456', 'KURNIA SENJAYA');
INSERT INTO "public"."suppliers" VALUES (458, NULL, NULL, '0457', 'SINURAT');
INSERT INTO "public"."suppliers" VALUES (459, NULL, NULL, '0458', 'HANAFI');
INSERT INTO "public"."suppliers" VALUES (460, NULL, NULL, '0459', 'YUSUF 249');
INSERT INTO "public"."suppliers" VALUES (461, NULL, NULL, '0460', 'FERANCHICE');
INSERT INTO "public"."suppliers" VALUES (462, NULL, NULL, '0461', 'PT VISTA MEGAH LESTARI (602)');
INSERT INTO "public"."suppliers" VALUES (463, NULL, NULL, '0462', 'TWIG HOUSE/KIOK (TH)');
INSERT INTO "public"."suppliers" VALUES (464, NULL, NULL, '0463', 'MELIA (616/722)');
INSERT INTO "public"."suppliers" VALUES (465, NULL, NULL, '0464', 'JUMINI');
INSERT INTO "public"."suppliers" VALUES (466, NULL, NULL, '0465', 'TRI JAYA/SYLVIA SUMARTO');
INSERT INTO "public"."suppliers" VALUES (467, NULL, NULL, '0466', 'YOHAN ONGGARA');
INSERT INTO "public"."suppliers" VALUES (468, NULL, NULL, '0467', 'CYNTIA DEVY');
INSERT INTO "public"."suppliers" VALUES (469, NULL, NULL, '0468', 'KING FASHION');
INSERT INTO "public"."suppliers" VALUES (470, NULL, NULL, '0469', 'KHATAM');
INSERT INTO "public"."suppliers" VALUES (471, NULL, NULL, '0470', 'BERLINA (BA)');
INSERT INTO "public"."suppliers" VALUES (472, NULL, NULL, '0471', 'VALENTIA/DIVA FASHION');
INSERT INTO "public"."suppliers" VALUES (473, NULL, NULL, '0472', 'PT ADETEX');
INSERT INTO "public"."suppliers" VALUES (474, NULL, NULL, '0473', 'KO KIKI ( KI )');
INSERT INTO "public"."suppliers" VALUES (475, NULL, NULL, '0474', 'ZULKIFLI/MR HONG');
INSERT INTO "public"."suppliers" VALUES (476, NULL, NULL, '0475', 'NANA COLL/BENTLEY');
INSERT INTO "public"."suppliers" VALUES (477, NULL, NULL, '0476', 'TERA LOVIANA');
INSERT INTO "public"."suppliers" VALUES (478, NULL, NULL, '0477', 'UNGARAN');
INSERT INTO "public"."suppliers" VALUES (479, NULL, NULL, '0478', 'BLESINDO');
INSERT INTO "public"."suppliers" VALUES (480, NULL, NULL, '0479', 'UK MANDIRI/BUDIONO');
INSERT INTO "public"."suppliers" VALUES (481, NULL, NULL, '0480', 'MSK/MASUKAYA');
INSERT INTO "public"."suppliers" VALUES (482, NULL, NULL, '0481', 'FEMALE FASHION/HANNY DESIGN');
INSERT INTO "public"."suppliers" VALUES (483, NULL, NULL, '0482', 'GOLDEN FLOWER');
INSERT INTO "public"."suppliers" VALUES (484, NULL, NULL, '0483', 'BUSANA EXPORT');
INSERT INTO "public"."suppliers" VALUES (485, NULL, NULL, '0484', 'HDR');
INSERT INTO "public"."suppliers" VALUES (486, NULL, NULL, '0485', 'ANTON SASMITA/LONG INDUSTRI');
INSERT INTO "public"."suppliers" VALUES (487, NULL, NULL, '0486', 'PT BMA');
INSERT INTO "public"."suppliers" VALUES (488, NULL, NULL, '0487', 'PT CAS (253/418/503/638/275)');
INSERT INTO "public"."suppliers" VALUES (489, NULL, NULL, '0488', 'HAIKAL');
INSERT INTO "public"."suppliers" VALUES (490, NULL, NULL, '0489', 'INDRAWATI');
INSERT INTO "public"."suppliers" VALUES (491, NULL, NULL, '0490', 'TOHA (TA)');
INSERT INTO "public"."suppliers" VALUES (492, NULL, NULL, '0491', 'FENTY/YOLA (288)');
INSERT INTO "public"."suppliers" VALUES (493, NULL, NULL, '0492', 'JASON INTI GARMENT');
INSERT INTO "public"."suppliers" VALUES (494, NULL, NULL, '0493', 'JE T AIME/LINNA EFFERIN');
INSERT INTO "public"."suppliers" VALUES (495, NULL, NULL, '0494', 'CANIA URESI/SELVI(303)');
INSERT INTO "public"."suppliers" VALUES (496, NULL, NULL, '0495', 'K.E.T');
INSERT INTO "public"."suppliers" VALUES (497, NULL, NULL, '0496', 'KOTA BUNGA/THOMAS SIHOMBING');
INSERT INTO "public"."suppliers" VALUES (498, NULL, NULL, '0497', 'RICKO RIDWAN ( RR )');
INSERT INTO "public"."suppliers" VALUES (499, NULL, NULL, '0498', 'ELEN/MADELAINE (EM)');
INSERT INTO "public"."suppliers" VALUES (500, NULL, NULL, '0499', 'IRA S');
INSERT INTO "public"."suppliers" VALUES (501, NULL, NULL, '0500', 'ALNA');
INSERT INTO "public"."suppliers" VALUES (502, NULL, NULL, '0501', 'MEGA IMPEXINDO/PRAKASH N M');
INSERT INTO "public"."suppliers" VALUES (503, NULL, NULL, '0502', 'MILLENIA');
INSERT INTO "public"."suppliers" VALUES (504, NULL, NULL, '0503', 'WALUYO/PSR CIPANAS');
INSERT INTO "public"."suppliers" VALUES (505, NULL, NULL, '0504', 'WINA');
INSERT INTO "public"."suppliers" VALUES (506, NULL, NULL, '0505', 'KINGS/PA ALVIN');
INSERT INTO "public"."suppliers" VALUES (507, NULL, NULL, '0506', 'FREUNDIN COLL');
INSERT INTO "public"."suppliers" VALUES (508, NULL, NULL, '0507', 'ETHNIC INDONESIA');
INSERT INTO "public"."suppliers" VALUES (509, NULL, NULL, '0508', 'FENTIE JUVE');
INSERT INTO "public"."suppliers" VALUES (510, NULL, NULL, '0509', 'RIZAL');
INSERT INTO "public"."suppliers" VALUES (511, NULL, NULL, '0510', 'TK ARDILLA');
INSERT INTO "public"."suppliers" VALUES (512, NULL, NULL, '0511', 'ACING');
INSERT INTO "public"."suppliers" VALUES (513, NULL, NULL, '0512', 'YANTO/BECXXA');
INSERT INTO "public"."suppliers" VALUES (514, NULL, NULL, '0513', 'TK CIPANAS');
INSERT INTO "public"."suppliers" VALUES (515, NULL, NULL, '0514', 'PANCA TUNGGAL (PT)');
INSERT INTO "public"."suppliers" VALUES (516, NULL, NULL, '0515', 'WAJEDI');
INSERT INTO "public"."suppliers" VALUES (517, NULL, NULL, '0516', 'INSPORT/BONAR ( IB )');
INSERT INTO "public"."suppliers" VALUES (518, NULL, NULL, '0517', 'MR SIN');
INSERT INTO "public"."suppliers" VALUES (519, NULL, NULL, '0518', 'SPLISH SPLASH');
INSERT INTO "public"."suppliers" VALUES (520, NULL, NULL, '0519', 'ABDILAH (FADILA/437/535)');
INSERT INTO "public"."suppliers" VALUES (521, NULL, NULL, '0520', 'PT CIPTA BUSANA JAYA');
INSERT INTO "public"."suppliers" VALUES (522, NULL, NULL, '0521', 'NASRUL ( NS )');
INSERT INTO "public"."suppliers" VALUES (523, NULL, NULL, '0522', 'PT KANCHAN JAYA');
INSERT INTO "public"."suppliers" VALUES (524, NULL, NULL, '0523', 'KAFIAT PRIMA');
INSERT INTO "public"."suppliers" VALUES (525, NULL, NULL, '0524', 'PT LEVIS STRAUSS INDONESIA');
INSERT INTO "public"."suppliers" VALUES (526, NULL, NULL, '0525', 'SB KIM');
INSERT INTO "public"."suppliers" VALUES (527, NULL, NULL, '0526', 'BATAMTEX');
INSERT INTO "public"."suppliers" VALUES (528, NULL, NULL, '0527', 'KINS SWALAYAN');
INSERT INTO "public"."suppliers" VALUES (529, NULL, NULL, '0528', 'PERDANA GARMENT');
INSERT INTO "public"."suppliers" VALUES (530, NULL, NULL, '0529', 'GAUD');
INSERT INTO "public"."suppliers" VALUES (531, NULL, NULL, '0530', 'BLOOMING/IING');
INSERT INTO "public"."suppliers" VALUES (532, NULL, NULL, '0531', 'FAISAL (651)');
INSERT INTO "public"."suppliers" VALUES (533, NULL, NULL, '0532', 'LUMINA GARMENT/BUDI');
INSERT INTO "public"."suppliers" VALUES (534, NULL, NULL, '0533', 'ANITA S/TEA (594)');
INSERT INTO "public"."suppliers" VALUES (535, NULL, NULL, '0534', 'PT RAJA BUSANA');
INSERT INTO "public"."suppliers" VALUES (536, NULL, NULL, '0535', 'YUSACK');
INSERT INTO "public"."suppliers" VALUES (537, NULL, NULL, '0536', 'ARTA GLORI BUNGA');
INSERT INTO "public"."suppliers" VALUES (538, NULL, NULL, '0537', 'NOVY/OKY SUGIRI');
INSERT INTO "public"."suppliers" VALUES (539, NULL, NULL, '0538', 'LELLY (009)');
INSERT INTO "public"."suppliers" VALUES (540, NULL, NULL, '0539', 'NOUVELLE/BPK DIDI');
INSERT INTO "public"."suppliers" VALUES (541, NULL, NULL, '0540', 'ACONG');
INSERT INTO "public"."suppliers" VALUES (542, NULL, NULL, '0541', 'ERATEX');
INSERT INTO "public"."suppliers" VALUES (543, NULL, NULL, '0542', 'JAYA ABADI/FIRMAN F H');
INSERT INTO "public"."suppliers" VALUES (544, NULL, NULL, '0543', 'NITA ANGGRAENI');
INSERT INTO "public"."suppliers" VALUES (545, NULL, NULL, '0544', 'LITTLE INK');
INSERT INTO "public"."suppliers" VALUES (546, NULL, NULL, '0545', 'LEMBANG INDAH GARMENT/VICTOR HERLIM');
INSERT INTO "public"."suppliers" VALUES (547, NULL, NULL, '0546', 'ICE JEANS/JIMMY BUSANA');
INSERT INTO "public"."suppliers" VALUES (548, NULL, NULL, '0547', 'RISKA');
INSERT INTO "public"."suppliers" VALUES (549, NULL, NULL, '0548', 'LILY YU/INDO PRIMA');
INSERT INTO "public"."suppliers" VALUES (550, NULL, NULL, '0549', 'WINS FASHION');
INSERT INTO "public"."suppliers" VALUES (551, NULL, NULL, '0550', 'BENNY (INDIA)/PT SURYA KENCANA');
INSERT INTO "public"."suppliers" VALUES (552, NULL, NULL, '0551', 'YANSEN');
INSERT INTO "public"."suppliers" VALUES (553, NULL, NULL, '0552', 'DIANA/MAKMUR SENTOSA');
INSERT INTO "public"."suppliers" VALUES (554, NULL, NULL, '0553', 'UUNG SUJATNIKA');
INSERT INTO "public"."suppliers" VALUES (555, NULL, NULL, '0554', 'HARRY/CANIA');
INSERT INTO "public"."suppliers" VALUES (556, NULL, NULL, '0555', 'IMELDA');
INSERT INTO "public"."suppliers" VALUES (557, NULL, NULL, '0556', 'IDRUS');
INSERT INTO "public"."suppliers" VALUES (558, NULL, NULL, '0557', 'HADI LIEM');
INSERT INTO "public"."suppliers" VALUES (559, NULL, NULL, '0558', 'ANGGI ( AG )');
INSERT INTO "public"."suppliers" VALUES (560, NULL, NULL, '0559', 'SRITEX');
INSERT INTO "public"."suppliers" VALUES (561, NULL, NULL, '0560', 'CABAZON');
INSERT INTO "public"."suppliers" VALUES (562, NULL, NULL, '0561', 'AYEP ( AP )');
INSERT INTO "public"."suppliers" VALUES (563, NULL, NULL, '0562', 'PT SALLY/TOTONG');
INSERT INTO "public"."suppliers" VALUES (564, NULL, NULL, '0563', 'KERIS GALERIE');
INSERT INTO "public"."suppliers" VALUES (565, NULL, NULL, '0564', 'KHARISMA JAYA');
INSERT INTO "public"."suppliers" VALUES (566, NULL, NULL, '0565', 'AGUSTIN');
INSERT INTO "public"."suppliers" VALUES (567, NULL, NULL, '0566', 'NATA/GRITANIA');
INSERT INTO "public"."suppliers" VALUES (568, NULL, NULL, '0567', 'MIKE S HOUSE/CATTY');
INSERT INTO "public"."suppliers" VALUES (569, NULL, NULL, '0568', 'PT.CHUNG SHUN');
INSERT INTO "public"."suppliers" VALUES (570, NULL, NULL, '0569', 'SCOLL');
INSERT INTO "public"."suppliers" VALUES (571, NULL, NULL, '0570', 'GUY GARMENT');
INSERT INTO "public"."suppliers" VALUES (572, NULL, NULL, '0571', 'ONEAL/MUHAMMAD HAFIDZ');
INSERT INTO "public"."suppliers" VALUES (573, NULL, NULL, '0572', 'TUNAS DARMA');
INSERT INTO "public"."suppliers" VALUES (574, NULL, NULL, '0573', 'IRA');
INSERT INTO "public"."suppliers" VALUES (575, NULL, NULL, '0574', 'XANADU');
INSERT INTO "public"."suppliers" VALUES (576, NULL, NULL, '0575', 'XANDA');
INSERT INTO "public"."suppliers" VALUES (577, NULL, NULL, '0576', 'CALISTA');
INSERT INTO "public"."suppliers" VALUES (578, NULL, NULL, '0577', 'ANITA S/ TEA (550)');
INSERT INTO "public"."suppliers" VALUES (579, NULL, NULL, '0578', 'M JOHAN ( 109/201/304/664)');
INSERT INTO "public"."suppliers" VALUES (580, NULL, NULL, '0579', 'MINA');
INSERT INTO "public"."suppliers" VALUES (581, NULL, NULL, '0580', 'DIAMOND/KURNIAWAN');
INSERT INTO "public"."suppliers" VALUES (582, NULL, NULL, '0581', 'MEI-MEI/MARTIN (645)');
INSERT INTO "public"."suppliers" VALUES (583, NULL, NULL, '0582', 'FO MIX');
INSERT INTO "public"."suppliers" VALUES (584, NULL, NULL, '0583', 'RIA');
INSERT INTO "public"."suppliers" VALUES (585, NULL, NULL, '0584', 'SUHANDI (248)');
INSERT INTO "public"."suppliers" VALUES (586, NULL, NULL, '0585', 'PT VISTA MEGAH LESTARI (477)');
INSERT INTO "public"."suppliers" VALUES (587, NULL, NULL, '0586', 'AMOUR/DIDI');
INSERT INTO "public"."suppliers" VALUES (588, NULL, NULL, '0587', 'BAMBANG');
INSERT INTO "public"."suppliers" VALUES (589, NULL, NULL, '0588', 'LANI SETIADI');
INSERT INTO "public"."suppliers" VALUES (590, NULL, NULL, '0589', 'HANNIE / MY JOY');
INSERT INTO "public"."suppliers" VALUES (591, NULL, NULL, '0590', 'IVAN JOESTAN');
INSERT INTO "public"."suppliers" VALUES (592, NULL, NULL, '0591', 'NENEN');
INSERT INTO "public"."suppliers" VALUES (593, NULL, NULL, '0592', 'RIDWAN');
INSERT INTO "public"."suppliers" VALUES (594, NULL, NULL, '0593', 'ELIZABETH');
INSERT INTO "public"."suppliers" VALUES (595, NULL, NULL, '0594', 'BETTY');
INSERT INTO "public"."suppliers" VALUES (596, NULL, NULL, '0595', 'KATHERINE');
INSERT INTO "public"."suppliers" VALUES (597, NULL, NULL, '0596', 'AMOEBA');
INSERT INTO "public"."suppliers" VALUES (598, NULL, NULL, '0597', 'V SUGIHARTO');
INSERT INTO "public"."suppliers" VALUES (599, NULL, NULL, '0598', 'FOREVER SALE');
INSERT INTO "public"."suppliers" VALUES (600, NULL, NULL, '0599', 'MELIA (479/722)');
INSERT INTO "public"."suppliers" VALUES (601, NULL, NULL, '0600', 'INKO BINA');
INSERT INTO "public"."suppliers" VALUES (602, NULL, NULL, '0601', 'DEDI');
INSERT INTO "public"."suppliers" VALUES (603, NULL, NULL, '0602', 'BERNARD WILLY');
INSERT INTO "public"."suppliers" VALUES (604, NULL, NULL, '0603', 'KRISTAL');
INSERT INTO "public"."suppliers" VALUES (605, NULL, NULL, '0604', 'RENA');
INSERT INTO "public"."suppliers" VALUES (606, NULL, NULL, '0605', 'ALEX JAYA');
INSERT INTO "public"."suppliers" VALUES (607, NULL, NULL, '0606', 'CORIE MANDIRI GARMINDO/CHYNTYA');
INSERT INTO "public"."suppliers" VALUES (608, NULL, NULL, '0607', 'FANNEKE');
INSERT INTO "public"."suppliers" VALUES (609, NULL, NULL, '0608', 'ERIX KRISTIANTO');
INSERT INTO "public"."suppliers" VALUES (610, NULL, NULL, '0609', 'NOVI/BOLA RATU');
INSERT INTO "public"."suppliers" VALUES (611, NULL, NULL, '0610', 'SETIA AGUNG');
INSERT INTO "public"."suppliers" VALUES (612, NULL, NULL, '0611', 'DADANG RUSLAN');
INSERT INTO "public"."suppliers" VALUES (613, NULL, NULL, '0612', 'YANTI');
INSERT INTO "public"."suppliers" VALUES (614, NULL, NULL, '0613', 'ULE COLLECTION');
INSERT INTO "public"."suppliers" VALUES (615, NULL, NULL, '0614', 'IRNA');
INSERT INTO "public"."suppliers" VALUES (616, NULL, NULL, '0615', 'PT PRIMA MANDIR INTISENTOSA');
INSERT INTO "public"."suppliers" VALUES (617, NULL, NULL, '0616', 'SUSIE');
INSERT INTO "public"."suppliers" VALUES (618, NULL, NULL, '0617', 'TANTI (032)');
INSERT INTO "public"."suppliers" VALUES (619, NULL, NULL, '0618', 'BABY TEAM');
INSERT INTO "public"."suppliers" VALUES (620, NULL, NULL, '0619', 'PT CAS (253/418/503/638/275)');
INSERT INTO "public"."suppliers" VALUES (621, NULL, NULL, '0620', 'VINS PRODUCTION');
INSERT INTO "public"."suppliers" VALUES (622, NULL, NULL, '0621', 'ANTONI (ANTON PADANG)');
INSERT INTO "public"."suppliers" VALUES (623, NULL, NULL, '0622', 'MEDIATECH/FELIX');
INSERT INTO "public"."suppliers" VALUES (624, NULL, NULL, '0623', 'PETER');
INSERT INTO "public"."suppliers" VALUES (625, NULL, NULL, '0624', 'HERMAWAN LEMBANG');
INSERT INTO "public"."suppliers" VALUES (626, NULL, NULL, '0625', 'MEI MEI (598)');
INSERT INTO "public"."suppliers" VALUES (627, NULL, NULL, '0626', 'SUSI LESMANA');
INSERT INTO "public"."suppliers" VALUES (628, NULL, NULL, '0627', 'SHERLY/CAKRAWALA MULTI BUSANA (252)');
INSERT INTO "public"."suppliers" VALUES (629, NULL, NULL, '0628', 'AGNES TAN');
INSERT INTO "public"."suppliers" VALUES (630, NULL, NULL, '0629', 'AAT');
INSERT INTO "public"."suppliers" VALUES (631, NULL, NULL, '0630', 'DIANA CHRISTIEN');
INSERT INTO "public"."suppliers" VALUES (632, NULL, NULL, '0631', 'FAIZAL (548)');
INSERT INTO "public"."suppliers" VALUES (633, NULL, NULL, '0632', 'KUMALA JKT/SHAYLA');
INSERT INTO "public"."suppliers" VALUES (634, NULL, NULL, '0633', 'WITA/KARTINI');
INSERT INTO "public"."suppliers" VALUES (635, NULL, NULL, '0634', 'TINA/FOUR STARS');
INSERT INTO "public"."suppliers" VALUES (636, NULL, NULL, '0635', 'SINAR ANUGERAH');
INSERT INTO "public"."suppliers" VALUES (637, NULL, NULL, '0636', 'HANNY ATMAJA');
INSERT INTO "public"."suppliers" VALUES (638, NULL, NULL, '0637', 'DARMADJI (386)');
INSERT INTO "public"."suppliers" VALUES (639, NULL, NULL, '0638', 'HERMAN/MEGA CIPTA GARMINDO');
INSERT INTO "public"."suppliers" VALUES (640, NULL, NULL, '0639', 'PHILLIPS-VAN HEUSEN/SHELLY');
INSERT INTO "public"."suppliers" VALUES (641, NULL, NULL, '0640', 'PT BPG');
INSERT INTO "public"."suppliers" VALUES (642, NULL, NULL, '0641', 'JIMMY/CUN KING');
INSERT INTO "public"."suppliers" VALUES (643, NULL, NULL, '0642', 'NAILA NOVARANTI');
INSERT INTO "public"."suppliers" VALUES (644, NULL, NULL, '0643', 'PT. DEWHIRST');
INSERT INTO "public"."suppliers" VALUES (645, NULL, NULL, '0644', 'TEGUH/YOSSANO');
INSERT INTO "public"."suppliers" VALUES (646, NULL, NULL, '0645', 'ENJANG');
INSERT INTO "public"."suppliers" VALUES (647, NULL, NULL, '0646', 'EDI HARMONI');
INSERT INTO "public"."suppliers" VALUES (648, NULL, NULL, '0647', 'CHA-CHA/MELISA');
INSERT INTO "public"."suppliers" VALUES (649, NULL, NULL, '0648', 'LUSY');
INSERT INTO "public"."suppliers" VALUES (650, NULL, NULL, '0649', 'ARIFIN FLORENZA TEXTILE');
INSERT INTO "public"."suppliers" VALUES (651, NULL, NULL, '0650', 'JCA SIANG- SIANG');
INSERT INTO "public"."suppliers" VALUES (652, NULL, NULL, '0651', 'PT SRI REJEKI');
INSERT INTO "public"."suppliers" VALUES (653, NULL, NULL, '0652', 'VIVI');
INSERT INTO "public"."suppliers" VALUES (654, NULL, NULL, '0653', 'SONU BHOJWANI');
INSERT INTO "public"."suppliers" VALUES (655, NULL, NULL, '0654', 'KUSWANTO');
INSERT INTO "public"."suppliers" VALUES (656, NULL, NULL, '0655', 'YANG-YANG');
INSERT INTO "public"."suppliers" VALUES (657, NULL, NULL, '0656', 'SHIRLY L/LILY FASHION');
INSERT INTO "public"."suppliers" VALUES (658, NULL, NULL, '0657', 'ROBERT');
INSERT INTO "public"."suppliers" VALUES (659, NULL, NULL, '0658', 'TAJUR (BOGOR)');
INSERT INTO "public"."suppliers" VALUES (660, NULL, NULL, '0659', 'KOTA BUNGA/BP SURYA');
INSERT INTO "public"."suppliers" VALUES (661, NULL, NULL, '0660', 'JEANI');
INSERT INTO "public"."suppliers" VALUES (662, NULL, NULL, '0661', 'SHELLY/PVH');
INSERT INTO "public"."suppliers" VALUES (663, NULL, NULL, '0662', 'IWAN/LALA');
INSERT INTO "public"."suppliers" VALUES (664, NULL, NULL, '0663', 'YOPIE');
INSERT INTO "public"."suppliers" VALUES (665, NULL, NULL, '0664', 'BUANA SPORT/INDRA (718/728)');
INSERT INTO "public"."suppliers" VALUES (666, NULL, NULL, '0665', 'IWAN/ANDI');
INSERT INTO "public"."suppliers" VALUES (667, NULL, NULL, '0666', 'ACHEN');
INSERT INTO "public"."suppliers" VALUES (668, NULL, NULL, '0667', 'RICKY');
INSERT INTO "public"."suppliers" VALUES (669, NULL, NULL, '0668', 'MELIA479/616');
INSERT INTO "public"."suppliers" VALUES (670, NULL, NULL, '0669', 'YANTO WINATA');
INSERT INTO "public"."suppliers" VALUES (671, NULL, NULL, '0670', 'BDM');
INSERT INTO "public"."suppliers" VALUES (672, NULL, NULL, '0671', 'ASEP P');
INSERT INTO "public"."suppliers" VALUES (673, NULL, NULL, '0672', 'PETER BARU');
INSERT INTO "public"."suppliers" VALUES (674, NULL, NULL, '0673', 'ANEKA JAYA');
INSERT INTO "public"."suppliers" VALUES (675, NULL, NULL, '0674', '"BUANA SPORT/INDRA 718');
INSERT INTO "public"."suppliers" VALUES (676, NULL, NULL, '0675', 'PT.DANLIRIS');
INSERT INTO "public"."suppliers" VALUES (677, NULL, NULL, '0676', 'H. MADI 164');
INSERT INTO "public"."suppliers" VALUES (678, NULL, NULL, '0677', 'AHMAD HOLOLI');
INSERT INTO "public"."suppliers" VALUES (679, NULL, NULL, '0678', 'RUDI KOSWARA/PT GEMPITA MITRAKARYA');
INSERT INTO "public"."suppliers" VALUES (680, NULL, NULL, '0679', 'SARINA CHANDRA');
INSERT INTO "public"."suppliers" VALUES (681, NULL, NULL, '0680', 'ANDREY');
INSERT INTO "public"."suppliers" VALUES (682, NULL, NULL, '0681', 'ALEX');
INSERT INTO "public"."suppliers" VALUES (683, NULL, NULL, '0682', 'YONAN');
INSERT INTO "public"."suppliers" VALUES (684, NULL, NULL, '0683', 'SEIZA/SIENDY');
INSERT INTO "public"."suppliers" VALUES (685, NULL, NULL, '0684', 'TIONG');
INSERT INTO "public"."suppliers" VALUES (686, NULL, NULL, '0685', 'CAKRAWALA MULTI BUSANA/YENNY');
INSERT INTO "public"."suppliers" VALUES (687, NULL, NULL, '0686', 'RUMAH GAYA');
INSERT INTO "public"."suppliers" VALUES (688, NULL, NULL, '0687', 'DINDRO SUSANTO');
INSERT INTO "public"."suppliers" VALUES (689, NULL, NULL, '0688', 'VICTORIA MITRA LESTARI');
INSERT INTO "public"."suppliers" VALUES (690, NULL, NULL, '0689', 'ANTON L BCA 745');
INSERT INTO "public"."suppliers" VALUES (691, NULL, NULL, '0690', 'HERMAN/TAMAN HOLIS');
INSERT INTO "public"."suppliers" VALUES (692, NULL, NULL, '0691', 'PABRIK BADJOE');
INSERT INTO "public"."suppliers" VALUES (693, NULL, NULL, '0692', 'DUNIA JAYA-PTB ANGKE KAV10-11');
INSERT INTO "public"."suppliers" VALUES (694, NULL, NULL, '0693', 'HEAVE CLOTHING');
INSERT INTO "public"."suppliers" VALUES (695, NULL, NULL, '0694', 'MITRA SUKSES BERSAMA/CBI');
INSERT INTO "public"."suppliers" VALUES (696, NULL, NULL, '0695', 'DENI');
INSERT INTO "public"."suppliers" VALUES (697, NULL, NULL, '0696', 'ARJAN/HARNES');
INSERT INTO "public"."suppliers" VALUES (698, NULL, NULL, '0697', 'VANESSA');
INSERT INTO "public"."suppliers" VALUES (699, NULL, NULL, '0698', 'HAMDANI');
INSERT INTO "public"."suppliers" VALUES (700, NULL, NULL, '0699', 'SUP EX JATI ENGGAL');
INSERT INTO "public"."suppliers" VALUES (701, NULL, NULL, '0700', 'TITO');
INSERT INTO "public"."suppliers" VALUES (702, NULL, NULL, '0701', 'FIE-FIE/SUN-SUN');
INSERT INTO "public"."suppliers" VALUES (703, NULL, NULL, '0702', 'NOVI/RIDWAN (NICE)');
INSERT INTO "public"."suppliers" VALUES (704, NULL, NULL, '0703', 'AWEN/KOTA KATUN');
INSERT INTO "public"."suppliers" VALUES (705, NULL, NULL, '0704', 'BUDI CIBUBUR');
INSERT INTO "public"."suppliers" VALUES (706, NULL, NULL, '0705', 'SHIEN-SHIEN');
INSERT INTO "public"."suppliers" VALUES (707, NULL, NULL, '0706', 'ARI JHONATAN');
INSERT INTO "public"."suppliers" VALUES (708, NULL, NULL, '0707', 'FARHAN UCOK');
INSERT INTO "public"."suppliers" VALUES (709, NULL, NULL, '0708', 'HASIL BORDIR');
INSERT INTO "public"."suppliers" VALUES (710, NULL, NULL, '0709', 'JOHANNA');
INSERT INTO "public"."suppliers" VALUES (711, NULL, NULL, '0710', 'SYAHRUL');
INSERT INTO "public"."suppliers" VALUES (712, NULL, NULL, '0711', 'MEDWEN');
INSERT INTO "public"."suppliers" VALUES (713, NULL, NULL, '0712', 'ANDRIAN');
INSERT INTO "public"."suppliers" VALUES (714, NULL, NULL, '0713', 'ESTI');
INSERT INTO "public"."suppliers" VALUES (715, NULL, NULL, '0714', 'HALIM RAJA FO');
INSERT INTO "public"."suppliers" VALUES (716, NULL, NULL, '0715', 'DAVID ANGGADA');
INSERT INTO "public"."suppliers" VALUES (717, NULL, NULL, '0716', 'YEYIN');
INSERT INTO "public"."suppliers" VALUES (718, NULL, NULL, '0717', 'MAISIR');
INSERT INTO "public"."suppliers" VALUES (719, NULL, NULL, '0718', 'JASWADI');
INSERT INTO "public"."suppliers" VALUES (720, NULL, NULL, '0719', 'STAR INDONESIA');
INSERT INTO "public"."suppliers" VALUES (721, NULL, NULL, '0720', 'ERIC');
INSERT INTO "public"."suppliers" VALUES (722, NULL, NULL, '0721', 'BAGOL SETIAWATI');
INSERT INTO "public"."suppliers" VALUES (723, NULL, NULL, '0722', 'SUP MIX BRG OB');
INSERT INTO "public"."suppliers" VALUES (724, NULL, NULL, '0723', 'JOSSANO');
INSERT INTO "public"."suppliers" VALUES (725, NULL, NULL, '0724', 'DAMAI TEXTILE');
INSERT INTO "public"."suppliers" VALUES (726, NULL, NULL, '0725', 'ELAINE (ELLEN)');
INSERT INTO "public"."suppliers" VALUES (727, NULL, NULL, '0726', 'TRI MANDIRI');
INSERT INTO "public"."suppliers" VALUES (728, NULL, NULL, '0727', 'PT.Aneka Label Indah');
INSERT INTO "public"."suppliers" VALUES (729, NULL, NULL, '0728', 'MASTER PRINT');
INSERT INTO "public"."suppliers" VALUES (730, NULL, NULL, '0729', 'PERBAIKAN 144');
INSERT INTO "public"."suppliers" VALUES (731, NULL, NULL, '0730', 'YOPIE BARU');
INSERT INTO "public"."suppliers" VALUES (732, NULL, NULL, '0731', 'KDS');
INSERT INTO "public"."suppliers" VALUES (733, NULL, NULL, '0732', 'NANA');
INSERT INTO "public"."suppliers" VALUES (734, NULL, NULL, '0733', 'SPM FASHION DISPLAY');
INSERT INTO "public"."suppliers" VALUES (735, NULL, NULL, '0734', 'DEDE');
INSERT INTO "public"."suppliers" VALUES (736, NULL, NULL, '0735', 'TOKO BERLIAN');
INSERT INTO "public"."suppliers" VALUES (737, NULL, NULL, '0736', 'JOHAN ANGGADA');
INSERT INTO "public"."suppliers" VALUES (738, NULL, NULL, '0737', 'JHON KHATAM');
INSERT INTO "public"."suppliers" VALUES (739, NULL, NULL, '0738', 'MAICIN KHATAM');
INSERT INTO "public"."suppliers" VALUES (740, NULL, NULL, '0739', 'CI IYEN');
INSERT INTO "public"."suppliers" VALUES (741, NULL, NULL, '0740', 'ANDY PRNT');
INSERT INTO "public"."suppliers" VALUES (742, NULL, NULL, '0741', 'MAGENTA');
INSERT INTO "public"."suppliers" VALUES (743, NULL, NULL, '0742', 'YAYU');
INSERT INTO "public"."suppliers" VALUES (744, NULL, NULL, '0743', 'TWIG HOUSE ( KONSINYASI )');
INSERT INTO "public"."suppliers" VALUES (745, NULL, NULL, '0744', 'UD STYLE/LENNY S');
INSERT INTO "public"."suppliers" VALUES (746, NULL, NULL, '0745', 'KAYDEE');
INSERT INTO "public"."suppliers" VALUES (747, NULL, NULL, '0746', 'HERLINA K');
INSERT INTO "public"."suppliers" VALUES (748, NULL, NULL, '0747', 'PT ADETEX');
INSERT INTO "public"."suppliers" VALUES (749, NULL, NULL, '0748', 'CELLINE SILVER');
INSERT INTO "public"."suppliers" VALUES (750, NULL, NULL, '0749', 'SYLVIE/JENNY');
INSERT INTO "public"."suppliers" VALUES (751, NULL, NULL, '0750', 'C GAMA CLAUDIANA');
INSERT INTO "public"."suppliers" VALUES (752, NULL, NULL, '0751', 'MUNDO');
INSERT INTO "public"."suppliers" VALUES (753, NULL, NULL, '0752', 'IRWAN');
INSERT INTO "public"."suppliers" VALUES (754, NULL, NULL, '0753', 'CANDRA');
INSERT INTO "public"."suppliers" VALUES (755, NULL, NULL, '0754', 'I KIKI ( KONSINYASI) 853');
INSERT INTO "public"."suppliers" VALUES (756, NULL, NULL, '0755', 'SHIAW HUNG ( KONSINYASI )');
INSERT INTO "public"."suppliers" VALUES (757, NULL, NULL, '0756', 'ALDI FASHION');
INSERT INTO "public"."suppliers" VALUES (758, NULL, NULL, '0757', 'NING/SARIMBIT');
INSERT INTO "public"."suppliers" VALUES (759, NULL, NULL, '0758', 'PRIMABEL');
INSERT INTO "public"."suppliers" VALUES (760, NULL, NULL, '0759', 'I KUANG');
INSERT INTO "public"."suppliers" VALUES (761, NULL, NULL, '0760', 'SANGWOO');
INSERT INTO "public"."suppliers" VALUES (762, NULL, NULL, '0761', 'P ANDREW');
INSERT INTO "public"."suppliers" VALUES (763, NULL, NULL, '0762', 'WINS FASHION K');
INSERT INTO "public"."suppliers" VALUES (764, NULL, NULL, '0763', 'STEVEN K');
INSERT INTO "public"."suppliers" VALUES (765, NULL, NULL, '0764', 'PT WIWA TEXTILE /UD TEKSTIL BERDIKARI');
INSERT INTO "public"."suppliers" VALUES (766, NULL, NULL, '0765', 'RUDI CEMPAKA 620');
INSERT INTO "public"."suppliers" VALUES (767, NULL, NULL, '0766', 'KIM IN SOO ( KONSINYASI)');
INSERT INTO "public"."suppliers" VALUES (768, NULL, NULL, '0767', 'PT PRIMA PERAHU A (KONSINYASI)');
INSERT INTO "public"."suppliers" VALUES (769, NULL, NULL, '0768', 'PT PERKASA S.L.K');
INSERT INTO "public"."suppliers" VALUES (770, NULL, NULL, '0769', 'PT FAMILI KEKAL ABADI ( KONS )');
INSERT INTO "public"."suppliers" VALUES (771, NULL, NULL, '0770', 'SUNARDI SIMANORA ( KONSY )');
INSERT INTO "public"."suppliers" VALUES (772, NULL, NULL, '0771', 'PT GEMILANG INTI LESTARINDO');
INSERT INTO "public"."suppliers" VALUES (773, NULL, NULL, '0772', 'CV BATIK MARTA');
INSERT INTO "public"."suppliers" VALUES (774, NULL, NULL, '0773', 'SANGKHIONG');
INSERT INTO "public"."suppliers" VALUES (775, NULL, NULL, '0774', 'ARIWARNI ( PT GAYA INDOMODEL)');
INSERT INTO "public"."suppliers" VALUES (776, NULL, NULL, '0775', 'CV KARYA JAYA MANDIRI SAKTI');
INSERT INTO "public"."suppliers" VALUES (777, NULL, NULL, '0776', 'ANIMALE');
INSERT INTO "public"."suppliers" VALUES (778, NULL, NULL, '0777', 'FANNEKE (KONSY)');
INSERT INTO "public"."suppliers" VALUES (779, NULL, NULL, '0778', 'NADIRA');
INSERT INTO "public"."suppliers" VALUES (780, NULL, NULL, '0779', 'KIKI');
INSERT INTO "public"."suppliers" VALUES (781, NULL, NULL, '0780', 'ACING');
INSERT INTO "public"."suppliers" VALUES (782, NULL, NULL, '0781', 'PT BATU KARAS/LILIAN');
INSERT INTO "public"."suppliers" VALUES (783, NULL, NULL, '0782', 'ANITA TEA ( KONSY)');
INSERT INTO "public"."suppliers" VALUES (784, NULL, NULL, '0783', 'JE T AIME/LINNA EFERINA');
INSERT INTO "public"."suppliers" VALUES (785, NULL, NULL, '0784', 'BENNY T (KONSY)');
INSERT INTO "public"."suppliers" VALUES (786, NULL, NULL, '0785', 'SPEX SYMBOL /DANAR DONO');
INSERT INTO "public"."suppliers" VALUES (787, NULL, NULL, '0786', 'UD JAYA UTAMA');
INSERT INTO "public"."suppliers" VALUES (788, NULL, NULL, '0787', 'TEGUH /YOSSANO KONSY');
INSERT INTO "public"."suppliers" VALUES (789, NULL, NULL, '0788', 'WILLIAM KONSY (WS)');
INSERT INTO "public"."suppliers" VALUES (790, NULL, NULL, '0789', 'ANDY LUKMAN KONS');
INSERT INTO "public"."suppliers" VALUES (791, NULL, NULL, '0790', 'KUMALA JAKARTA');
INSERT INTO "public"."suppliers" VALUES (792, NULL, NULL, '0791', 'SURYA INDAH');
INSERT INTO "public"."suppliers" VALUES (793, NULL, NULL, '0792', 'PT FAMILI KEKAL ABADI (KONY)');
INSERT INTO "public"."suppliers" VALUES (794, NULL, NULL, '0793', 'JEANY (KONSY)');
INSERT INTO "public"."suppliers" VALUES (795, NULL, NULL, '0794', 'TK MODO /I YENNY');
INSERT INTO "public"."suppliers" VALUES (796, NULL, NULL, '0795', 'ANTON BCA (KONSY)');
INSERT INTO "public"."suppliers" VALUES (797, NULL, NULL, '0796', 'BPK KOSWARA/KONSY');
INSERT INTO "public"."suppliers" VALUES (798, NULL, NULL, '0797', 'I KIKI ACC U/PROPERTY');
INSERT INTO "public"."suppliers" VALUES (799, NULL, NULL, '0798', 'P ALVIN (RELAXOGY)');
INSERT INTO "public"."suppliers" VALUES (800, NULL, NULL, '0799', 'I KIKI 2 ( KONSY)');
INSERT INTO "public"."suppliers" VALUES (801, NULL, NULL, '0800', 'BAKRIE');
INSERT INTO "public"."suppliers" VALUES (802, NULL, NULL, '0801', 'ANDRI CIE');
INSERT INTO "public"."suppliers" VALUES (803, NULL, NULL, '0802', 'SUPLER MIX GRD A');
INSERT INTO "public"."suppliers" VALUES (804, NULL, NULL, '0803', 'JAJAT');
INSERT INTO "public"."suppliers" VALUES (805, NULL, NULL, '0804', 'LENI (KONSYINYASI)');
INSERT INTO "public"."suppliers" VALUES (806, NULL, NULL, '0805', 'KETUT KRISBIANTORO');
INSERT INTO "public"."suppliers" VALUES (807, NULL, NULL, '0806', 'PT CAS WASHING');
INSERT INTO "public"."suppliers" VALUES (808, NULL, NULL, '0807', 'HENDRA/DINAMIS GARMENT');
INSERT INTO "public"."suppliers" VALUES (809, NULL, NULL, '0808', 'IVANA');
INSERT INTO "public"."suppliers" VALUES (810, NULL, NULL, '0809', 'ASIONG');
INSERT INTO "public"."suppliers" VALUES (811, NULL, NULL, '0810', 'DJ BUSANA');
INSERT INTO "public"."suppliers" VALUES (812, NULL, NULL, '0811', 'PT PINNACLE APPARELS/NORTWEST');
INSERT INTO "public"."suppliers" VALUES (813, NULL, NULL, '0812', '3 KYUNG SEUNG/DASUM MULYADI');
INSERT INTO "public"."suppliers" VALUES (814, NULL, NULL, '0813', 'SUKSES HAMINDO SEJAHTERA');
INSERT INTO "public"."suppliers" VALUES (815, NULL, NULL, '0814', '"I KIKI GMT 361');
INSERT INTO "public"."suppliers" VALUES (816, NULL, NULL, '0815', 'HIDAYAT');
INSERT INTO "public"."suppliers" VALUES (817, NULL, NULL, '0816', 'SARI KADARUSMAN');
INSERT INTO "public"."suppliers" VALUES (818, NULL, NULL, '0817', 'PT CAS');
INSERT INTO "public"."suppliers" VALUES (819, NULL, NULL, '0818', 'BLESSING/JERRY KEMANG');
INSERT INTO "public"."suppliers" VALUES (820, NULL, NULL, '0819', 'EDY HANGER');
INSERT INTO "public"."suppliers" VALUES (821, NULL, NULL, '0820', 'PT MAKMUR  INTERPACK');
INSERT INTO "public"."suppliers" VALUES (822, NULL, NULL, '0821', 'PT DARUL HIJRAH /HJ AYI');
INSERT INTO "public"."suppliers" VALUES (823, NULL, NULL, '0822', 'MR. RAJU');
INSERT INTO "public"."suppliers" VALUES (824, NULL, NULL, '0823', 'YULI BORDIR');
INSERT INTO "public"."suppliers" VALUES (825, NULL, NULL, '0824', 'BUDI JKT');
INSERT INTO "public"."suppliers" VALUES (826, NULL, NULL, '0825', 'MAISIR 906');
INSERT INTO "public"."suppliers" VALUES (827, NULL, NULL, '0826', 'GUNAWAN BARU');
INSERT INTO "public"."suppliers" VALUES (828, NULL, NULL, '0827', 'HENI YULIANA (DESSY)');
INSERT INTO "public"."suppliers" VALUES (829, NULL, NULL, '0828', 'NURDIN');
INSERT INTO "public"."suppliers" VALUES (830, NULL, NULL, '0829', 'H. RAMLI');
INSERT INTO "public"."suppliers" VALUES (831, NULL, NULL, '0830', 'INDRA CEMPAKA');
INSERT INTO "public"."suppliers" VALUES (832, NULL, NULL, '0831', 'PT FOREVER GARMINDO');
INSERT INTO "public"."suppliers" VALUES (833, NULL, NULL, '0832', 'RACHEL');
INSERT INTO "public"."suppliers" VALUES (834, NULL, NULL, '0833', '"BUDI CIBUBUR 760');
INSERT INTO "public"."suppliers" VALUES (835, NULL, NULL, '0834', 'BUYUNG');
INSERT INTO "public"."suppliers" VALUES (836, NULL, NULL, '0835', 'SANTU RAJUT');
INSERT INTO "public"."suppliers" VALUES (837, NULL, NULL, '0836', 'GRACE CHRISTIANI');
INSERT INTO "public"."suppliers" VALUES (838, NULL, NULL, '0837', 'PT GA/MAYOR JUN');
INSERT INTO "public"."suppliers" VALUES (839, NULL, NULL, '0838', 'JHON UCOK');
INSERT INTO "public"."suppliers" VALUES (840, NULL, NULL, '0839', 'IBU TINI');
INSERT INTO "public"."suppliers" VALUES (841, NULL, NULL, '0840', 'MUJI');
INSERT INTO "public"."suppliers" VALUES (842, NULL, NULL, '0841', 'MITRA SANDANG ABADI');
INSERT INTO "public"."suppliers" VALUES (843, NULL, NULL, '0842', 'ENI PAMULANG');
INSERT INTO "public"."suppliers" VALUES (844, NULL, NULL, '0843', 'JUKIUS JUPRIANTO');
INSERT INTO "public"."suppliers" VALUES (845, NULL, NULL, '0844', 'CATUR MANUNGGAL PERKASA');
INSERT INTO "public"."suppliers" VALUES (846, NULL, NULL, '0845', 'BPK DONA');
INSERT INTO "public"."suppliers" VALUES (847, NULL, NULL, '0846', 'BPK KAMPRET');
INSERT INTO "public"."suppliers" VALUES (848, NULL, NULL, '0847', 'EVI HADIYANY');
INSERT INTO "public"."suppliers" VALUES (849, NULL, NULL, '0848', 'ERNI SENTUL');
INSERT INTO "public"."suppliers" VALUES (850, NULL, NULL, '0849', 'HAJI HADI');
INSERT INTO "public"."suppliers" VALUES (851, NULL, NULL, '0850', 'TOKO BONEKA M2');
INSERT INTO "public"."suppliers" VALUES (852, NULL, NULL, '0851', 'JHONY');
INSERT INTO "public"."suppliers" VALUES (853, NULL, NULL, '0852', 'WAWAN KUMIS');
INSERT INTO "public"."suppliers" VALUES (854, NULL, NULL, '0853', 'JATI ENGGAL');
INSERT INTO "public"."suppliers" VALUES (855, NULL, NULL, '0854', 'LISA COLLECTION');
INSERT INTO "public"."suppliers" VALUES (856, NULL, NULL, '0855', 'MR LEE');
INSERT INTO "public"."suppliers" VALUES (857, NULL, NULL, '0856', 'ROLLA DESIGN');
INSERT INTO "public"."suppliers" VALUES (858, NULL, NULL, '0857', 'MR MANIS');
INSERT INTO "public"."suppliers" VALUES (859, NULL, NULL, '0858', 'SUHANDI 248');
INSERT INTO "public"."suppliers" VALUES (860, NULL, NULL, '0859', 'SIAN SIAN');
INSERT INTO "public"."suppliers" VALUES (861, NULL, NULL, '0860', 'HENDRI');
INSERT INTO "public"."suppliers" VALUES (862, NULL, NULL, '0861', 'HENGKI/MIMI');
INSERT INTO "public"."suppliers" VALUES (863, NULL, NULL, '0862', 'MAISIR 773');
INSERT INTO "public"."suppliers" VALUES (864, NULL, NULL, '0863', 'BING SURABAYA');
INSERT INTO "public"."suppliers" VALUES (865, NULL, NULL, '0864', 'MJR KAIN');
INSERT INTO "public"."suppliers" VALUES (866, NULL, NULL, '0865', 'SELVY');
INSERT INTO "public"."suppliers" VALUES (867, NULL, NULL, '0866', 'ANTON GUNADI/JOKO');
INSERT INTO "public"."suppliers" VALUES (868, NULL, NULL, '0867', 'RAY');
INSERT INTO "public"."suppliers" VALUES (869, NULL, NULL, '0868', 'DELVIN');
INSERT INTO "public"."suppliers" VALUES (870, NULL, NULL, '0869', 'PT BIDAYA/LIVING ROOM');
INSERT INTO "public"."suppliers" VALUES (871, NULL, NULL, '0870', 'TRANSFORM MANEQUINS');
INSERT INTO "public"."suppliers" VALUES (872, NULL, NULL, '0871', 'WAHAN TATA');
INSERT INTO "public"."suppliers" VALUES (873, NULL, NULL, '0872', 'SULISTIONO');
INSERT INTO "public"."suppliers" VALUES (874, NULL, NULL, '0873', 'IYAN/OMOH');
INSERT INTO "public"."suppliers" VALUES (875, NULL, NULL, '0874', 'HERMAN BARU');
INSERT INTO "public"."suppliers" VALUES (876, NULL, NULL, '0875', 'H BENNY');
INSERT INTO "public"."suppliers" VALUES (877, NULL, NULL, '0876', 'CERITA');
INSERT INTO "public"."suppliers" VALUES (878, NULL, NULL, '0877', 'PADDU');
INSERT INTO "public"."suppliers" VALUES (879, NULL, NULL, '0878', 'BEYOST');
INSERT INTO "public"."suppliers" VALUES (880, NULL, NULL, '0879', 'MESSA');
INSERT INTO "public"."suppliers" VALUES (881, NULL, NULL, '0880', 'PT SHIN WOO');
INSERT INTO "public"."suppliers" VALUES (882, NULL, NULL, '0881', 'ARMAN');
INSERT INTO "public"."suppliers" VALUES (883, NULL, NULL, '0882', 'MEI LING');
INSERT INTO "public"."suppliers" VALUES (884, NULL, NULL, '0883', 'EKA KARYA/IBU RINA');
INSERT INTO "public"."suppliers" VALUES (885, NULL, NULL, '0884', 'HERU');
INSERT INTO "public"."suppliers" VALUES (886, NULL, NULL, '0885', 'TAKUMI/BPK ROY');
INSERT INTO "public"."suppliers" VALUES (887, NULL, NULL, '0886', 'HARRY SOLO');
INSERT INTO "public"."suppliers" VALUES (888, NULL, NULL, '0887', 'SRI SEMARANG');
INSERT INTO "public"."suppliers" VALUES (889, NULL, NULL, '0888', 'HERMAN LISNA');
INSERT INTO "public"."suppliers" VALUES (890, NULL, NULL, '0889', 'MR PRAVEEN');
INSERT INTO "public"."suppliers" VALUES (891, NULL, NULL, '0890', 'PT SUN JONG');
INSERT INTO "public"."suppliers" VALUES (892, NULL, NULL, '0891', 'TINA');
INSERT INTO "public"."suppliers" VALUES (893, NULL, NULL, '0892', 'AMEI');
INSERT INTO "public"."suppliers" VALUES (894, NULL, NULL, '0893', '"H MADI 164');
INSERT INTO "public"."suppliers" VALUES (895, NULL, NULL, '0894', 'DADANG');
INSERT INTO "public"."suppliers" VALUES (896, NULL, NULL, '0895', 'SUTAR');
INSERT INTO "public"."suppliers" VALUES (897, NULL, NULL, '0896', 'DENI/MAJU JAYA GLOBAL');
INSERT INTO "public"."suppliers" VALUES (898, NULL, NULL, '0897', 'AMING');
INSERT INTO "public"."suppliers" VALUES (899, NULL, NULL, '0898', 'RUDIANTO');
INSERT INTO "public"."suppliers" VALUES (900, NULL, NULL, '0899', 'HAPID/ABA STICK');
INSERT INTO "public"."suppliers" VALUES (901, NULL, NULL, '0900', 'HENDRA');
INSERT INTO "public"."suppliers" VALUES (902, NULL, NULL, '0901', 'PT GRAHA BUSANA GEMILANG/JAYA SENTOSA');
INSERT INTO "public"."suppliers" VALUES (903, NULL, NULL, '0902', 'IYAN JUNED');
INSERT INTO "public"."suppliers" VALUES (904, NULL, NULL, '0903', 'PT.PRIMA MENARA UTAMA/HIDAYAT');
INSERT INTO "public"."suppliers" VALUES (905, NULL, NULL, '0904', 'HASBI');
INSERT INTO "public"."suppliers" VALUES (906, NULL, NULL, '0905', 'PT SAHABAT UNGGUL');
INSERT INTO "public"."suppliers" VALUES (907, NULL, NULL, '0906', 'UDIN SAPUTRA');
INSERT INTO "public"."suppliers" VALUES (908, NULL, NULL, '0907', 'BUDI CARZABETA');
INSERT INTO "public"."suppliers" VALUES (909, NULL, NULL, '0908', 'WILLIAM HERMAN');
INSERT INTO "public"."suppliers" VALUES (910, NULL, NULL, '0909', 'SUSANTO');
INSERT INTO "public"."suppliers" VALUES (911, NULL, NULL, '0910', 'I LIA');
INSERT INTO "public"."suppliers" VALUES (912, NULL, NULL, '0911', 'BANDUNG FO');
INSERT INTO "public"."suppliers" VALUES (913, NULL, NULL, '0912', 'LIVIA LING LING');
INSERT INTO "public"."suppliers" VALUES (914, NULL, NULL, '0913', 'SUPLIER HADIAH');
INSERT INTO "public"."suppliers" VALUES (915, NULL, NULL, '0914', 'PT. Biginusindo Permai');
INSERT INTO "public"."suppliers" VALUES (916, NULL, NULL, '0915', 'PT. Bumi Pusaka Adhi Perkasa');
INSERT INTO "public"."suppliers" VALUES (917, NULL, NULL, '0916', 'PT. Karunia Dharma Sejahtera');
INSERT INTO "public"."suppliers" VALUES (918, NULL, NULL, '0917', 'PT. Cipta Kreasisandang Mandiri');
INSERT INTO "public"."suppliers" VALUES (919, NULL, NULL, '0918', 'CV. Sunflower');
INSERT INTO "public"."suppliers" VALUES (920, NULL, NULL, '0919', 'PT. Turangga Kertakencana');
INSERT INTO "public"."suppliers" VALUES (921, NULL, NULL, '0920', 'CV. Elatindo Kharisma Jaya');
INSERT INTO "public"."suppliers" VALUES (922, NULL, NULL, '0921', 'PT. Vidiaelok Lestari Garmindo');
INSERT INTO "public"."suppliers" VALUES (923, NULL, NULL, '0922', 'PT. Berkat Usaha Jaya');
INSERT INTO "public"."suppliers" VALUES (924, NULL, NULL, '0923', 'PT. Adiwarna Busana Lestari');
INSERT INTO "public"."suppliers" VALUES (925, NULL, NULL, '0924', 'PT. Ballin Ekalestari');
INSERT INTO "public"."suppliers" VALUES (926, NULL, NULL, '0925', 'PT. Central Network Indonesia');
INSERT INTO "public"."suppliers" VALUES (927, NULL, NULL, '0926', 'PT. Citra Crocotama Internasional');
INSERT INTO "public"."suppliers" VALUES (928, NULL, NULL, '0927', 'PT. Citra Surya Pasific');
INSERT INTO "public"."suppliers" VALUES (929, NULL, NULL, '0928', 'PT. Bina Busana Internusa');
INSERT INTO "public"."suppliers" VALUES (930, NULL, NULL, '0929', 'PT. Citra Busana Jaya Pertiwi');
INSERT INTO "public"."suppliers" VALUES (931, NULL, NULL, '0930', 'PT. Defasindo Kreasi Prima');
INSERT INTO "public"."suppliers" VALUES (932, NULL, NULL, '0931', 'PT. Harindotama Mandiri');
INSERT INTO "public"."suppliers" VALUES (933, NULL, NULL, '0932', 'PT. Indonesia Wacoal');
INSERT INTO "public"."suppliers" VALUES (934, NULL, NULL, '0933', 'PT. Konia Putra Lestari');
INSERT INTO "public"."suppliers" VALUES (935, NULL, NULL, '0934', 'PT. Mega Indah Pratama');
INSERT INTO "public"."suppliers" VALUES (936, NULL, NULL, '0935', 'PT. Mega Perintis');
INSERT INTO "public"."suppliers" VALUES (937, NULL, NULL, '0936', 'PT. Picarinjaya Abadi');
INSERT INTO "public"."suppliers" VALUES (938, NULL, NULL, '0937', 'PT. Point Mas Cemerlang');
INSERT INTO "public"."suppliers" VALUES (939, NULL, NULL, '0938', 'PT. Primajaya Pantes Garment');
INSERT INTO "public"."suppliers" VALUES (940, NULL, NULL, '0939', 'PT. Rodeo Kerta Kencana');
INSERT INTO "public"."suppliers" VALUES (941, NULL, NULL, '0940', 'PT. Dharmarindo ANugerah Surya');
INSERT INTO "public"."suppliers" VALUES (942, NULL, NULL, '0941', 'PT. Sumber Kreasi Fumiko');
INSERT INTO "public"."suppliers" VALUES (943, NULL, NULL, '0942', 'PT. Tri Anugrah Fashion');
INSERT INTO "public"."suppliers" VALUES (944, NULL, NULL, '0943', 'PT. Joey Sasmita Lencana');
INSERT INTO "public"."suppliers" VALUES (945, NULL, NULL, '0944', 'PT. Jusindo Sumberprakarsa');
INSERT INTO "public"."suppliers" VALUES (946, NULL, NULL, '0945', 'PT. Kurnia Astasurya');
INSERT INTO "public"."suppliers" VALUES (947, NULL, NULL, '0946', 'PT. Rofina Indah Jaya');
INSERT INTO "public"."suppliers" VALUES (948, NULL, NULL, '0947', 'PT. Trinitas Mulia Abadi');
INSERT INTO "public"."suppliers" VALUES (949, NULL, NULL, '0948', 'PT.Tritunggal Esa Senanda');
INSERT INTO "public"."suppliers" VALUES (950, NULL, NULL, '0949', 'PT. Sumber Dipta Asia');
INSERT INTO "public"."suppliers" VALUES (951, NULL, NULL, '0950', 'PT. Tas Centre Cemerlang');
INSERT INTO "public"."suppliers" VALUES (952, NULL, NULL, '0951', 'PT. Warna Mardhika');
INSERT INTO "public"."suppliers" VALUES (953, NULL, NULL, '0952', 'PT. Madonna Variakreasi');
INSERT INTO "public"."suppliers" VALUES (954, NULL, NULL, '0953', 'STOCK CENTRE');
INSERT INTO "public"."suppliers" VALUES (955, NULL, NULL, '0954', 'PT.AMBASSADOR GARMINDO');
INSERT INTO "public"."suppliers" VALUES (956, NULL, NULL, '0955', 'CV.Sinergi Sukses Indonesia');
INSERT INTO "public"."suppliers" VALUES (957, NULL, NULL, '0956', 'AGUNG KAMDI');
INSERT INTO "public"."suppliers" VALUES (958, NULL, NULL, '0957', 'DAVID PAGARSIH');
INSERT INTO "public"."suppliers" VALUES (959, NULL, NULL, '0958', 'DONI ANGGADA');
INSERT INTO "public"."suppliers" VALUES (960, NULL, NULL, '0959', 'THIRD DAY CLOTHING (ALWIN)');
INSERT INTO "public"."suppliers" VALUES (961, NULL, NULL, '0960', 'CV.SINAR RAYA ABADI (RAY)');
INSERT INTO "public"."suppliers" VALUES (962, NULL, NULL, '0961', 'TOHO');
INSERT INTO "public"."suppliers" VALUES (963, NULL, NULL, '0962', 'PRIMA MAKMUR HANGER');
INSERT INTO "public"."suppliers" VALUES (964, NULL, NULL, '0963', 'BPK. IYUS');
INSERT INTO "public"."suppliers" VALUES (965, NULL, NULL, '0964', 'YUKARI WAHYU');
INSERT INTO "public"."suppliers" VALUES (966, NULL, NULL, '0965', 'AAT ANTON');
INSERT INTO "public"."suppliers" VALUES (967, NULL, NULL, '0966', 'YURICA (MY JOY)');
INSERT INTO "public"."suppliers" VALUES (968, NULL, NULL, '0967', 'EPISODE');
INSERT INTO "public"."suppliers" VALUES (969, NULL, NULL, '0968', 'IAN PORIS');
INSERT INTO "public"."suppliers" VALUES (970, NULL, NULL, '0969', 'KENCANA PLASTIK');
INSERT INTO "public"."suppliers" VALUES (971, NULL, NULL, '0970', 'IBU VONI');
INSERT INTO "public"."suppliers" VALUES (972, NULL, NULL, '0971', 'ARI KHATAM');
INSERT INTO "public"."suppliers" VALUES (973, NULL, NULL, '0972', 'PT STARINDO JAYA UTAMA/IBU II');
INSERT INTO "public"."suppliers" VALUES (974, NULL, NULL, '0973', 'HUSEIN ANTON');
INSERT INTO "public"."suppliers" VALUES (975, NULL, NULL, '0974', 'OKI');
INSERT INTO "public"."suppliers" VALUES (976, NULL, NULL, '0975', 'PT PRIMA GRACINDO');
INSERT INTO "public"."suppliers" VALUES (977, NULL, NULL, '0976', 'BANDAR GANTUNGAN');
INSERT INTO "public"."suppliers" VALUES (978, NULL, NULL, '0977', 'INSPORT BONAR ( KONSY )');
INSERT INTO "public"."suppliers" VALUES (979, NULL, NULL, '0978', 'RON 88');
INSERT INTO "public"."suppliers" VALUES (980, NULL, NULL, '0979', 'CV HARISMA');
INSERT INTO "public"."suppliers" VALUES (981, NULL, NULL, '0980', 'BARATA BATIK ( KONSY )');
INSERT INTO "public"."suppliers" VALUES (982, NULL, NULL, '0981', 'CV COLLIN VICTORY');
INSERT INTO "public"."suppliers" VALUES (983, NULL, NULL, '0982', 'CV. KARUNIA TRITUNGGAL ( ALWIN )');
INSERT INTO "public"."suppliers" VALUES (984, NULL, NULL, '0983', 'PD LAYAR');
INSERT INTO "public"."suppliers" VALUES (985, NULL, NULL, '0984', 'LAMONTE.id');
INSERT INTO "public"."suppliers" VALUES (986, NULL, NULL, '0985', 'ESTHER');
INSERT INTO "public"."suppliers" VALUES (987, NULL, NULL, '0986', 'JULIANA');
INSERT INTO "public"."suppliers" VALUES (988, NULL, NULL, '0987', 'KO CUCU');
INSERT INTO "public"."suppliers" VALUES (989, NULL, NULL, '0988', 'GHINA SECRET');
INSERT INTO "public"."suppliers" VALUES (990, NULL, NULL, '0989', 'PT. PERUSAHAAN LOGAM BIMA');
INSERT INTO "public"."suppliers" VALUES (991, NULL, NULL, '0990', 'KO CUCU KONSINYASI');
INSERT INTO "public"."suppliers" VALUES (992, NULL, NULL, '0991', 'RUMAH MODE FO');
INSERT INTO "public"."suppliers" VALUES (993, NULL, NULL, '0992', 'NIBIRU');
INSERT INTO "public"."suppliers" VALUES (994, NULL, NULL, '0993', 'NURYANTO');
INSERT INTO "public"."suppliers" VALUES (995, NULL, NULL, '0994', 'ACHEN');
INSERT INTO "public"."suppliers" VALUES (996, NULL, NULL, '0995', 'YURI/CERITA');
INSERT INTO "public"."suppliers" VALUES (997, NULL, NULL, '0996', 'MR KIM');
INSERT INTO "public"."suppliers" VALUES (998, NULL, NULL, '0997', 'PD PONDOK TAS');
INSERT INTO "public"."suppliers" VALUES (999, NULL, NULL, '0998', 'ILUVA JAYA TAS');
INSERT INTO "public"."suppliers" VALUES (1000, NULL, NULL, '0999', 'IAN / IMPERIAL');
INSERT INTO "public"."suppliers" VALUES (1001, NULL, NULL, '1000', 'HAT VS HEAD');
INSERT INTO "public"."suppliers" VALUES (1002, NULL, NULL, '1001', 'DADANG POLISI');
INSERT INTO "public"."suppliers" VALUES (1003, NULL, NULL, '1002', 'ARKIDS');
INSERT INTO "public"."suppliers" VALUES (1004, NULL, NULL, '1003', '267 SHOP');
INSERT INTO "public"."suppliers" VALUES (1005, NULL, NULL, '1004', 'Sis - Ex');
INSERT INTO "public"."suppliers" VALUES (1006, NULL, NULL, '1005', 'BENY CIBINONG');
INSERT INTO "public"."suppliers" VALUES (1007, NULL, NULL, '1006', 'PUBLICITY');
INSERT INTO "public"."suppliers" VALUES (1008, NULL, NULL, '1007', 'BRAND REVOLUTION');
INSERT INTO "public"."suppliers" VALUES (1009, NULL, NULL, '1008', 'MINGALA');
INSERT INTO "public"."suppliers" VALUES (1010, NULL, NULL, '1009', 'POOKIE');
INSERT INTO "public"."suppliers" VALUES (1011, NULL, NULL, '1010', 'NESSA SLEEPWEAR');
INSERT INTO "public"."suppliers" VALUES (1012, NULL, NULL, '1011', 'BODY BOSS');
INSERT INTO "public"."suppliers" VALUES (1013, NULL, NULL, '1012', 'BINTANG GAJAH');
INSERT INTO "public"."suppliers" VALUES (1014, NULL, NULL, '1013', 'DUNIA SOUVENIR BANDUNG');
INSERT INTO "public"."suppliers" VALUES (1015, NULL, NULL, '1014', 'MAHKOTA KENCANA');
